// Copyright cases where the works are images (from the course's case table).
// Image A is the plaintiff's work, image B the defendant's. Which cases have
// images is listed in assets/cases/manifest.json (see assets/cases/README.md).

export const CASE_GROUPS = [
  { id: 'liable', title: 'Liability', blurb: 'Infringement found; fair use rejected.' },
  { id: 'fairuse', title: 'No liability — fair use', blurb: 'Copying excused as fair use.' },
  {
    id: 'nosim',
    title: 'No liability — no substantial similarity or no protectable work',
    blurb: 'What was taken was not protectable expression, or not enough of it.',
  },
];

export const CASES = [
  {
    id: 'rogers-v-koons',
    group: 'liable',
    name: 'Rogers v. Koons',
    cite: '960 F.2d 301 (2d Cir. 1992)',
    pairing: 'Puppies photo → String of Puppies sculpture',
    note: 'Copying conceded; fair use rejected.',
  },
  {
    id: 'steinberg-v-columbia',
    group: 'liable',
    name: 'Steinberg v. Columbia Pictures Indus.',
    cite: '663 F. Supp. 706 (S.D.N.Y. 1987)',
    pairing: 'View of the World from 9th Avenue → Moscow on the Hudson poster',
    note: 'SJ for plaintiff.',
  },
  {
    id: 'gaylord-v-us',
    group: 'liable',
    name: 'Gaylord v. United States',
    cite: '595 F.3d 1364 (Fed. Cir. 2010)',
    pairing: 'Korean War Veterans Memorial sculpture → USPS stamp',
    note: 'Fair use rejected.',
  },
  {
    id: 'friedman-v-guetta',
    group: 'liable',
    name: 'Friedman v. Guetta',
    cite: '2011 WL 3510890 (C.D. Cal. May 27, 2011)',
    pairing: 'Run-DMC photo → Mr. Brainwash',
    note: 'Fair use rejected on SJ.',
  },
  {
    id: 'monge-v-maya',
    group: 'liable',
    name: 'Monge v. Maya Magazines',
    cite: '688 F.3d 1164 (9th Cir. 2012)',
    pairing: 'Secret wedding photos → magazine',
    note: 'Unpublished works; fair use rejected.',
  },
  {
    id: 'morris-v-guetta',
    group: 'liable',
    name: 'Morris v. Guetta',
    cite: '2013 WL 440127 (C.D. Cal. Feb. 4, 2013)',
    pairing: 'Sid Vicious photo → Mr. Brainwash',
    note: 'Fair use rejected.',
  },
  {
    id: 'brammer-v-violent-hues',
    group: 'liable',
    name: 'Brammer v. Violent Hues Prods.',
    cite: '922 F.3d 255 (4th Cir. 2019)',
    pairing: 'Adams Morgan photo → film festival website',
    note: 'Casual “transformative” claim rejected.',
  },
  {
    id: 'seuss-v-comicmix',
    group: 'liable',
    name: 'Dr. Seuss Enters. v. ComicMix',
    cite: '983 F.3d 443 (9th Cir. 2020)',
    pairing: 'Seuss illustrations → Oh, the Places You’ll Boldly Go!',
    note: 'Satire, not parody.',
  },
  {
    id: 'warhol-v-goldsmith',
    group: 'liable',
    name: 'Andy Warhol Found. v. Goldsmith',
    cite: '598 U.S. 508 (2023)',
    pairing: 'Goldsmith Prince photo → Orange Prince licensed to Condé Nast',
    note: 'Factor one for Goldsmith.',
    caution:
      'The Court resolved only the first fair use factor as to the 2016 licensing, not the creation of the Prince Series. Cite it narrowly.',
  },
  {
    id: 'leibovitz-v-paramount',
    group: 'fairuse',
    name: 'Leibovitz v. Paramount Pictures',
    cite: '137 F.3d 109 (2d Cir. 1998)',
    pairing: 'Pregnant Demi Moore cover → Naked Gun 33⅓ poster',
    note: 'Parody.',
  },
  {
    id: 'nunez-v-caribbean',
    group: 'fairuse',
    name: 'Núñez v. Caribbean Int’l News',
    cite: '235 F.3d 18 (1st Cir. 2000)',
    pairing: 'Miss Puerto Rico photos → newspaper',
    note: 'News reporting.',
  },
  {
    id: 'kelly-v-arriba',
    group: 'fairuse',
    name: 'Kelly v. Arriba Soft',
    cite: '336 F.3d 811 (9th Cir. 2003)',
    pairing: 'Photos → search engine thumbnails',
  },
  {
    id: 'mattel-v-walking-mountain',
    group: 'fairuse',
    name: 'Mattel v. Walking Mountain Prods.',
    cite: '353 F.3d 792 (9th Cir. 2003)',
    pairing: 'Barbie → Food Chain Barbie photographs',
    note: 'Parody.',
  },
  {
    id: 'bill-graham-v-dk',
    group: 'fairuse',
    name: 'Bill Graham Archives v. Dorling Kindersley',
    cite: '448 F.3d 605 (2d Cir. 2006)',
    pairing: 'Concert posters → reduced images in a book timeline',
  },
  {
    id: 'blanch-v-koons',
    group: 'fairuse',
    name: 'Blanch v. Koons',
    cite: '467 F.3d 244 (2d Cir. 2006)',
    pairing: 'Silk Sandals by Gucci → Niagara',
    note: 'Same artist, opposite result from Rogers.',
  },
  {
    id: 'perfect10-v-amazon',
    group: 'fairuse',
    name: 'Perfect 10 v. Amazon.com',
    cite: '508 F.3d 1146 (9th Cir. 2007)',
    pairing: 'Photos → Google Image thumbnails',
  },
  {
    id: 'seltzer-v-green-day',
    group: 'fairuse',
    name: 'Seltzer v. Green Day',
    cite: '725 F.3d 1170 (9th Cir. 2013)',
    pairing: 'Scream Icon → stage video backdrop',
  },
  {
    id: 'kienitz-v-sconnie',
    group: 'fairuse',
    name: 'Kienitz v. Sconnie Nation',
    cite: '766 F.3d 756 (7th Cir. 2014)',
    pairing: 'Mayor Soglin photo → posterized t-shirt',
  },
  {
    id: 'katz-v-google',
    group: 'fairuse',
    name: 'Katz v. Google',
    cite: '802 F.3d 1178 (11th Cir. 2015)',
    pairing: 'Unflattering photo → critical blog',
  },
  {
    id: 'bridgeman-v-corel',
    group: 'nosim',
    name: 'Bridgeman Art Library v. Corel',
    cite: '36 F. Supp. 2d 191 (S.D.N.Y. 1999)',
    pairing: 'Transparencies of public-domain paintings',
    note: 'Slavish reproduction lacks originality.',
  },
  {
    id: 'ets-hokin-v-skyy',
    group: 'nosim',
    name: 'Ets-Hokin v. Skyy Spirits',
    cite: '323 F.3d 763 (9th Cir. 2003)',
    pairing: 'Vodka bottle product photos',
    note: 'Thin copyright; not substantially similar.',
  },
  {
    id: 'meshwerks-v-toyota',
    group: 'nosim',
    name: 'Meshwerks v. Toyota',
    cite: '528 F.3d 1258 (10th Cir. 2008)',
    pairing: 'Digital wireframe models of cars',
    note: 'Not original.',
  },
  {
    id: 'harney-v-sony',
    group: 'nosim',
    name: 'Harney v. Sony Pictures Television',
    cite: '704 F.3d 173 (1st Cir. 2013)',
    pairing: 'Photo → deliberate staged recreation',
    note: 'Only unprotected elements taken.',
  },
  {
    id: 'rentmeester-v-nike',
    group: 'nosim',
    name: 'Rentmeester v. Nike',
    cite: '883 F.3d 1111 (9th Cir. 2018)',
    pairing: 'Jordan photo → Nike photo and Jumpman logo',
    note: 'Idea/expression.',
  },
  {
    id: 'solid-oak-v-2k',
    group: 'nosim',
    name: 'Solid Oak Sketches v. 2K Games',
    cite: '449 F. Supp. 3d 333 (S.D.N.Y. 2020)',
    pairing: 'Tattoo designs → NBA 2K',
    note: 'De minimis, implied license, fair use.',
  },
];
