// The catalogue of tests ("engines"): what each one measures, how its score
// is read, the thresholds used for the verdict, and short teaching notes.
// Shared by the UI and the analysis worker.

export const GROUPS = [
  {
    id: 'neural',
    title: 'Neural copy detection',
    blurb:
      'Deep networks map each image to a vector ("embedding"); similar images land close together. SSCD is trained specifically to recognise copies, while CLIP and DINOv2 measure general visual or semantic resemblance.',
  },
  {
    id: 'objects',
    title: 'Objects',
    blurb:
      'An object detector (D-FINE, trained on the 365 everyday categories of Objects365) finds things like hats, pictures and tables in each image. The objects are paired up across the two images and compared one by one; the Objects tab shows the marked-up images.',
  },
  {
    id: 'exact',
    title: 'Exact & verbatim copies',
    blurb:
      'Bit-level checks. They only fire on literal copies: change a single byte or pixel and they report "different".',
  },
  {
    id: 'fuzzy',
    title: 'Fuzzy file hashes',
    blurb:
      'Forensic examiners and malware analysts compare files as byte sequences: these hashes tolerate small byte-level changes such as edited metadata or appended data. They do not see pictures — a re-saved JPEG shares almost no bytes with the original, however alike the two images look.',
  },
  {
    id: 'hash',
    title: 'Perceptual hashes',
    blurb:
      'Each image is reduced to a short fingerprint that survives resizing and re-compression. Fingerprints are compared by counting differing bits (Hamming distance). These are the workhorses of large-scale duplicate and abuse-material detection.',
  },
  {
    id: 'geometry',
    title: 'Keypoints & geometry',
    blurb:
      'Classic computer vision: find distinctive corners/blobs in both images, match them, and check whether one consistent geometric transform (a homography) explains the matches. Robust to cropping, scaling and rotation.',
  },
  {
    id: 'structure',
    title: 'Pixel & structural similarity',
    blurb:
      'Full-reference image-quality metrics. Image B is resized to image A’s dimensions and compared location by location, so they assume the two images are aligned.',
  },
  {
    id: 'color',
    title: 'Color & histograms',
    blurb:
      'Compare the overall distribution of colours or brightness, ignoring where they occur. Fast and invariant to geometry, but two unrelated images with similar palettes look alike.',
  },
  {
    id: 'texture',
    title: 'Texture & shape',
    blurb:
      'Classic computer-vision descriptors of texture (the grain, edges and patterns of a picture) and of shape (how its brightness is spread out). Each image is described on its own and the descriptions are compared, so most of these ignore crops of the other image but can be fooled by unrelated pictures with a similar look.',
  },
  {
    id: 'meta',
    title: 'Metadata',
    blurb: 'Information stored alongside the pixels (camera, timestamp). Easy to strip or forge.',
  },
];

const pct = (v) => `${(v * 100).toFixed(v >= 0.995 && v < 1 ? 1 : 0)}%`;
const f3 = (v) => v.toFixed(3);
const f2 = (v) => v.toFixed(2);
const bits = (n) => (d) => `${d} / ${n} bits`;

const HASH64 = { better: 'lower', match: 8, partial: 14, format: bits(64) };

export const ENGINES = [
  // ------------------------------------------------------------ neural
  {
    id: 'sscd',
    group: 'neural',
    name: 'SSCD copy detector',
    by: 'Meta AI · ResNet-50 · sscd_disc_mixup',
    featured: true,
    metric: 'cosine similarity of 512-d descriptors',
    better: 'higher',
    match: 0.75,
    partial: 0.5,
    format: f3,
    model: 'sscd',
    about:
      'A Self-Supervised Descriptor for image Copy Detection, trained to give near-identical vectors to an image and its edited copies (crops, overlays, colour changes, compression) while separating merely similar-looking photos.',
    thresholds:
      '≥ 0.75: copy (the SSCD authors report 90% precision at this point on the DISC2021 benchmark). 0.50–0.75: possible partial copy — Somepalli et al. treat scores above 0.5 as likely "partial object-level copies". Below 0.5: not a copy.',
    robust: ['resizing', 'compression', 'colour edits', 'overlays & text', 'flips', 'moderate crops'],
    weak: ['heavy crops of a small region', 'large rotations', 'redrawn or restyled copies'],
    refs: [
      { label: 'Pizzi et al., CVPR 2022', url: 'https://arxiv.org/abs/2202.10261' },
      { label: 'Code & models (MIT)', url: 'https://github.com/facebookresearch/sscd-copy-detection' },
    ],
    pipeline: 'Short edge resized to 288 px (bilinear), ImageNet normalisation — the preprocessing recommended in the SSCD README.',
  },
  {
    id: 'sscdAligned',
    group: 'neural',
    name: 'SSCD after alignment',
    by: 'SSCD on the shared region, with crop / rotation / perspective undone',
    metric: 'cosine similarity of SSCD descriptors of the aligned overlap',
    better: 'higher',
    match: 0.75,
    partial: 0.5,
    format: f3,
    model: 'sscd',
    about:
      'A copy detector looks at whole images, so a copy that was rotated, put in perspective, cut down to a corner or pasted into a larger picture can score low. This test first lines B up with A using the keypoint transform, then runs SSCD on just the region the two images share — the same comparison a person makes after holding the two side by side and turning one to match.',
    thresholds: 'Same scale as SSCD: ≥ 0.75 copy, 0.50–0.75 possible partial copy. Only runs when keypoint matching finds a consistent transform.',
    robust: ['rotation', 'perspective', 'heavy crops', 'copies pasted into a larger image'],
    weak: ['redrawn or restaged copies (no keypoint transform)', 'mirror images'],
    refs: [{ label: 'Pizzi et al., CVPR 2022 (SSCD)', url: 'https://arxiv.org/abs/2202.10261' }],
    pipeline: 'Keypoint homography (best of ORB, AKAZE, BRISK) → warp B into A’s frame (≤ 640 px) → crop both to the overlap, grey outside it → SSCD (short edge 288).',
  },
  {
    id: 'sscdLarge',
    group: 'neural',
    name: 'SSCD · replication-study setting',
    by: 'Meta AI · ResNeXt-101 · sscd_disc_large',
    featured: true,
    metric: 'cosine similarity of 1024-d descriptors',
    better: 'higher',
    match: 0.5,
    partial: null,
    format: f3,
    model: 'sscdLarge',
    about:
      'Reproduces how Somepalli et al. measured whether diffusion models replicate their training images, following the configuration in the authors’ published code: the large SSCD model with resize-256 / centre-crop-224 preprocessing. Only the centre crop is compared, so borders are ignored.',
    thresholds:
      '> 0.50: replication. Somepalli et al. found generations above 0.5 "exhibit strong visual similarities" and are "likely to be partial object-level copies" of training data; in the NeurIPS 2023 paper they used > 0.7 to find nearly identical duplicates in LAION.',
    robust: ['resizing', 'compression', 'colour edits', 'flips'],
    weak: ['content outside the centre crop', 'heavy crops', 'large rotations'],
    refs: [
      { label: 'Somepalli et al., NeurIPS 2023', url: 'https://arxiv.org/abs/2305.20086' },
      { label: 'Somepalli et al., CVPR 2023', url: 'https://arxiv.org/abs/2212.03860' },
      { label: 'DCR code', url: 'https://github.com/somepago/DCR' },
    ],
    pipeline: 'Resize short edge to 256 (bilinear), centre crop 224×224, normalise to [-1, 1] — exactly as in the DCR repository.',
  },
  {
    id: 'dino',
    group: 'neural',
    name: 'DINOv2 embedding',
    by: 'Meta AI · ViT-S/14',
    metric: 'cosine similarity of the CLS token',
    better: 'higher',
    match: 0.85,
    partial: 0.4,
    format: f3,
    model: 'dino',
    about:
      'A self-supervised vision transformer whose features capture object identity and layout. Widely used for image retrieval; it responds to "same object/scene" more than to "same pixels".',
    thresholds: '≥ 0.85: near-duplicate content. 0.40–0.85: same subject, pose or scene (a staged recreation of a photo scores about 0.5). Below 0.40: different content; unrelated photos score near 0. (Heuristic thresholds.)',
    robust: ['resizing', 'compression', 'colour edits', 'moderate crops', 'small rotations'],
    weak: ['flags different photos of the same object', 'large crops'],
    refs: [{ label: 'Oquab et al., 2023', url: 'https://arxiv.org/abs/2304.07193' }],
    pipeline: 'Resize short edge to 256 (bicubic), centre crop 224, ImageNet normalisation (Hugging Face preprocessing).',
  },
  {
    id: 'clip',
    group: 'neural',
    name: 'CLIP embedding',
    by: 'OpenAI · ViT-B/32',
    metric: 'cosine similarity of image embeddings',
    better: 'higher',
    match: 0.95,
    partial: 0.75,
    format: f3,
    model: 'clip',
    about:
      'CLIP was trained to match images with captions, so its embedding encodes what an image is about. Two different photos of a red sports car score high; it measures semantic similarity, not copying.',
    thresholds: '≥ 0.95: near-duplicate. 0.75–0.95: semantically similar (same kind of content). Below 0.75: different. Unrelated photos still typically score 0.4–0.6. (Heuristic thresholds.)',
    robust: ['almost every edit', 'style changes'],
    weak: ['cannot tell a copy from a new image of the same subject'],
    refs: [{ label: 'Radford et al., ICML 2021', url: 'https://arxiv.org/abs/2103.00020' }],
    pipeline: 'Resize short edge to 224 (bicubic), centre crop 224, CLIP normalisation (Hugging Face preprocessing).',
  },
  {
    id: 'dreamsim',
    group: 'neural',
    name: 'DreamSim — would people call them alike?',
    by: 'Fu et al., NeurIPS 2023 · OpenCLIP ViT-B/32 tuned on human judgments',
    metric: 'perceptual distance (0 = same, about 0.8 = unrelated)',
    better: 'lower',
    match: 0.12,
    partial: 0.4,
    format: f3,
    model: 'dreamsim',
    about:
      'DreamSim was trained on NIGHTS, 20,000 sets of human votes about which of two images looks more like a third, and agrees with those votes 95% of the time (this single-backbone version; 96% for the full ensemble). It responds to layout, pose, colour and subject together — the overall impression a person forms at a glance. That makes it the closest computational stand-in for the ordinary observer, with the same blind spot: it cannot tell protected expression from shared ideas or stock elements.',
    thresholds:
      '≤ 0.12: looks the same. 0.12–0.40: looks alike (a staged recreation of a photo scores about 0.3). Above 0.40: looks different; unrelated photos score about 0.8. Thresholds calibrated on the site’s benchmark (1% of unrelated pairs fall below 0.41).',
    robust: ['compression', 'colour edits', 'mirroring', 'mild crops', 'restaging the same scene'],
    weak: ['small pasted copies (collages)', 'large overlays'],
    refs: [
      { label: 'Fu et al., NeurIPS 2023', url: 'https://arxiv.org/abs/2306.09344' },
      { label: 'Code & weights (MIT)', url: 'https://github.com/ssundaram21/dreamsim' },
    ],
    pipeline: 'Bicubic resize to 224×224 (no crop), OpenCLIP ViT-B/32 with DreamSim’s LoRA weights merged, normalised embedding, distance = 1 − cosine.',
  },
  {
    id: 'lpips',
    group: 'neural',
    name: 'LPIPS perceptual distance',
    by: 'Zhang et al. · AlexNet v0.1',
    metric: 'learned perceptual distance (0 = identical)',
    better: 'lower',
    match: 0.2,
    partial: 0.4,
    format: f3,
    model: 'lpips',
    about:
      'Compares deep network activations location by location, calibrated against human judgements of how different two images look. Like SSIM it assumes aligned images, so geometric edits push it up.',
    thresholds: '≤ 0.20: perceptually close. 0.20–0.40: noticeably different. Above 0.40: different (unrelated images ≈ 0.6–0.8).',
    robust: ['compression', 'mild blur/noise'],
    weak: ['crops, flips, rotations (misalignment)'],
    refs: [{ label: 'Zhang et al., CVPR 2018', url: 'https://arxiv.org/abs/1801.03924' }],
    pipeline: 'Both images resized to A’s aspect ratio with a 256 px long side, scaled to [-1, 1].',
  },

  // ------------------------------------------------------------ objects
  {
    id: 'objects',
    group: 'objects',
    name: 'Object-level comparison',
    by: 'D-FINE-M detector · Objects365 · 365 categories',
    metric: 'objects paired across the two images, and how many changed',
    better: 'equal',
    model: 'dfine',
    about:
      'Detects objects in both images and pairs them up — by position when the images can be aligned with keypoints, otherwise by kind and appearance — then compares each pair: the pixels inside the object (when aligned) and the SSCD copy similarity of the two cut-outs.',
    thresholds:
      'Match: at least 80% of the objects appear in both images unchanged. Partial: at least half of them pair up. An aligned object counts as changed when more than 10% of its pixels change colour (ΔE₀₀ > 6) or its SSIM falls below 0.8.',
    robust: ['crops', 'rescaling', 'objects that move (matched by appearance)'],
    weak: ['things outside the 365 categories', 'small or hidden objects', 'stylised or abstract art'],
    refs: [
      { label: 'D-FINE (Peng et al., ICLR 2025)', url: 'https://arxiv.org/abs/2410.13842' },
      { label: 'Objects365 (Shao et al., ICCV 2019)', url: 'https://doi.org/10.1109/ICCV.2019.00852' },
    ],
    pipeline: 'Each image resized to 640×640; detections above 0.35 confidence; duplicates suppressed so each object keeps one label.',
  },

  {
    id: 'pose',
    group: 'objects',
    name: 'Body pose similarity',
    by: 'ViTPose-B (NeurIPS 2022) · 17 joints · Procrustes + OKS',
    metric: 'pose similarity of the best-matching people (0–1)',
    better: 'higher',
    match: 0.8,
    partial: 0.55,
    format: f2,
    model: 'pose',
    about:
      'Finds 17 body joints (eyes, shoulders, elbows, wrists, hips, knees, ankles) for each person the object detector found, then compares poses after removing position, size and rotation — and also against the mirror image. Each joint scores by how far it lands from its counterpart, relative to the size of the body (the COCO keypoint similarity). The overlay draws one pose on top of the other.',
    thresholds: '≥ 0.80: the same pose. 0.55–0.80: a similar pose (a staged recreation scores about 0.57). Below 0.55: different poses. Calibrated on a handful of pairs — a heuristic scale.',
    robust: ['scaling', 'mirroring', 'restyled or restaged photos', 'different people'],
    weak: ['hidden or cut-off limbs', 'crowds', 'unusual viewpoints'],
    refs: [
      { label: 'Xu et al., ViTPose, NeurIPS 2022', url: 'https://arxiv.org/abs/2204.12484' },
      { label: 'Rentmeester v. Nike, 883 F.3d 1111 (9th Cir. 2018)', url: 'https://cdn.ca9.uscourts.gov/datastore/opinions/2018/02/27/15-35509.pdf' },
    ],
  },

  // ------------------------------------------------------------ exact
  {
    id: 'sha256',
    group: 'exact',
    name: 'SHA-256 file hash',
    by: 'cryptographic digest of the file bytes',
    metric: 'exact equality',
    better: 'equal',
    about:
      'A cryptographic fingerprint of the file. Identical digests mean the files are byte-for-byte the same; any change (even metadata or re-saving at the same quality) produces a completely different digest.',
    thresholds: 'Identical digest ⇒ identical file. Otherwise the test says nothing about visual similarity.',
    robust: ['nothing — by design'],
    weak: ['any change at all, including invisible ones'],
    refs: [{ label: 'FIPS 180-4', url: 'https://csrc.nist.gov/pubs/fips/180-4/upd1/final' }],
  },
  {
    id: 'sha1',
    group: 'exact',
    name: 'SHA-1 file hash',
    by: 'legacy cryptographic digest',
    metric: 'exact equality',
    better: 'equal',
    about: 'Older 160-bit digest, still common in forensic tools. Deliberate collisions are practical (2017), so it should not be trusted against an adversary.',
    thresholds: 'Identical digest ⇒ identical file (barring a deliberate collision).',
    robust: ['nothing — by design'],
    weak: ['any change at all'],
    refs: [{ label: 'SHAttered (2017)', url: 'https://shattered.io/' }],
  },
  {
    id: 'md5',
    group: 'exact',
    name: 'MD5 file hash',
    by: 'legacy cryptographic digest',
    metric: 'exact equality',
    better: 'equal',
    about: 'The 128-bit digest used by many older hash databases. Collisions can be manufactured in seconds, so it only proves identity for non-adversarial data.',
    thresholds: 'Identical digest ⇒ identical file (barring a deliberate collision).',
    robust: ['nothing — by design'],
    weak: ['any change at all'],
    refs: [{ label: 'RFC 1321', url: 'https://www.rfc-editor.org/rfc/rfc1321' }],
  },
  {
    id: 'sha512',
    group: 'exact',
    name: 'SHA-512 file hash',
    by: 'longest SHA-2 digest',
    metric: 'exact equality',
    better: 'equal',
    about: 'The 512-bit member of the SHA-2 family, which some evidence-handling and archival standards ask for. A longer digest makes accidental or engineered collisions even less conceivable, but the test answers the same question as SHA-256: are these the same bytes?',
    thresholds: 'Identical digest ⇒ identical file.',
    robust: ['nothing — by design'],
    weak: ['any change at all'],
    refs: [{ label: 'FIPS 180-4', url: 'https://csrc.nist.gov/pubs/fips/180-4/upd1/final' }],
  },
  {
    id: 'sha3',
    group: 'exact',
    name: 'SHA3-256 file hash',
    by: 'Keccak sponge · FIPS 202',
    metric: 'exact equality',
    better: 'equal',
    about: 'The newest US standard hash, chosen by an open competition (2012) and built on an entirely different design from SHA-1 and SHA-2, so a weakness found in one family would not carry over. Same verdict as the other cryptographic hashes; listed to show the family tree.',
    thresholds: 'Identical digest ⇒ identical file.',
    robust: ['nothing — by design'],
    weak: ['any change at all'],
    refs: [{ label: 'FIPS 202', url: 'https://csrc.nist.gov/pubs/fips/202/final' }],
  },
  {
    id: 'blake2b',
    group: 'exact',
    name: 'BLAKE2b file hash',
    by: 'RFC 7693 · 256-bit digest',
    metric: 'exact equality',
    better: 'equal',
    about: 'A fast cryptographic hash popular in backup, deduplication and file-sync software (and the basis of BLAKE3). It is as strict as SHA-256: one changed byte gives an unrelated digest.',
    thresholds: 'Identical digest ⇒ identical file.',
    robust: ['nothing — by design'],
    weak: ['any change at all'],
    refs: [{ label: 'RFC 7693', url: 'https://www.rfc-editor.org/rfc/rfc7693' }],
  },
  {
    id: 'crc32',
    group: 'exact',
    name: 'CRC-32 checksum',
    by: 'cyclic redundancy check · zip / PNG / Ethernet',
    metric: 'exact equality',
    better: 'equal',
    about: 'A 32-bit checksum built to catch accidental corruption in transmission and storage — it is what ZIP and PNG files store to verify themselves. It is not a fingerprint you can rely on against anyone: matching files can be manufactured in milliseconds, and about one in four billion unrelated files collide by chance.',
    thresholds: 'Different checksum ⇒ different files. Equal checksum ⇒ very probably identical, absent deliberate tampering.',
    robust: ['nothing — by design'],
    weak: ['any change at all', 'deliberate collisions are trivial'],
    refs: [{ label: 'ISO 3309 / ITU-T V.42', url: 'https://www.itu.int/rec/T-REC-V.42' }],
  },
  {
    id: 'payload',
    group: 'exact',
    name: 'Same image data (metadata ignored)',
    by: 'SHA-256 of the compressed image data alone',
    metric: 'exact equality of the encoded image',
    better: 'equal',
    about:
      'Splits each file into its compressed picture (JPEG scans and tables, PNG image chunks, WebP bitstream) and its metadata (EXIF, XMP, IPTC, ICC, comments), and hashes only the picture. Equal hashes with different files mean somebody changed or stripped the metadata without re-saving the image.',
    thresholds: 'Identical: same encoded picture, so B was not re-compressed — only its metadata differs.',
    robust: ['metadata edits and removal'],
    weak: ['any re-save, even at the same quality', 'different file formats'],
    refs: [{ label: 'JPEG (ITU-T T.81)', url: 'https://www.w3.org/Graphics/JPEG/itu-t81.pdf' }],
  },
  {
    id: 'pixels',
    group: 'exact',
    name: 'Pixel-exact match',
    by: 'decoded RGBA values',
    metric: 'share of identical pixels',
    better: 'equal',
    about:
      'Decodes both files and compares every pixel. Catches identical images saved in different formats or with different metadata (e.g. PNG vs. lossless WebP), which file hashes miss.',
    thresholds: 'All pixels equal (and same dimensions) ⇒ identical image. Any lossy re-encoding breaks it.',
    robust: ['metadata changes', 'lossless format conversion'],
    weak: ['JPEG re-compression', 'any edit or resize'],
    refs: [],
  },
  {
    id: 'crop',
    group: 'exact',
    name: 'Verbatim crop search',
    by: 'template matching · OpenCV',
    metric: 'normalised cross-correlation of the best placement',
    better: 'higher',
    match: 0.97,
    partial: 0.9,
    format: f3,
    about:
      'Checks whether the smaller image appears inside the larger one at the same scale — a cut-out or screenshot of part of the image. When the best placement matches pixel-for-pixel it reports a verbatim (lossless) crop.',
    thresholds: '≥ 0.97: the smaller image is a crop of the larger one. 0.90–0.97: probable crop with edits/compression. Only runs when one image is smaller in both dimensions.',
    robust: ['compression', 'small brightness changes'],
    weak: ['rescaling', 'rotation', 'same-size images (not applicable)'],
    refs: [{ label: 'OpenCV matchTemplate', url: 'https://docs.opencv.org/4.x/df/dfb/group__imgproc__object.html' }],
  },

  // ------------------------------------------------------------ fuzzy file hashes
  {
    id: 'ssdeep',
    group: 'fuzzy',
    name: 'ssdeep',
    by: 'context-triggered piecewise hashing · Kornblum 2006',
    metric: 'match score 0–100',
    better: 'higher',
    match: 50,
    partial: 1,
    format: (v) => `${v} / 100`,
    about:
      'The fuzzy hash of digital forensics, used by law enforcement and in malware databases such as VirusTotal. It cuts the file into pieces at points chosen by the content itself, hashes each piece, and compares the two lists of piece-hashes like strings, so files that share long runs of bytes score high even when bytes were inserted or deleted elsewhere.',
    thresholds: '≥ 50: the files share most of their bytes. 1–49: they share some stretches. 0: no shared stretches — what every re-saved image gives, however alike the pictures (unrelated test images never scored above 0).',
    robust: ['metadata edits', 'appended or inserted data', 'local edits in uncompressed files'],
    weak: ['any re-compression (JPEG re-save, format change)', 'resizing', 'colour edits of compressed images'],
    refs: [
      { label: 'Kornblum, Digital Investigation 2006', url: 'https://doi.org/10.1016/j.diin.2006.06.015' },
      { label: 'ssdeep', url: 'https://ssdeep-project.github.io/ssdeep/' },
    ],
  },
  {
    id: 'tlsh',
    group: 'fuzzy',
    name: 'TLSH',
    by: 'Trend Micro locality-sensitive hash · Oliver et al. 2013',
    metric: 'distance (0 = identical)',
    better: 'lower',
    match: 50,
    partial: 100,
    format: (v) => String(v),
    about:
      'A 70-character digest summarising which byte triplets occur how often across the file, so similar files get nearby digests and can be searched at scale. VirusTotal shows it next to ssdeep. Like every byte-level measure it compares the encoded file, not the picture.',
    thresholds: '≤ 50: very similar files. 51–100: related. Above 100: unrelated as byte streams (unrelated test images were never closer than 162).',
    robust: ['metadata edits', 'small insertions anywhere in the file'],
    weak: ['re-compression', 'resizing', 'anything that changes most bytes'],
    refs: [
      { label: 'Oliver, Cheng & Chen, CTC 2013', url: 'https://doi.org/10.1109/CTC.2013.9' },
      { label: 'TLSH (Apache-2.0)', url: 'https://github.com/trendmicro/tlsh' },
    ],
  },

  {
    id: 'nilsimsa',
    group: 'fuzzy',
    name: 'Nilsimsa',
    by: 'locality-sensitive trigram hash · Damiani et al. 2004',
    metric: 'score from −128 to 128 (128 = same digest)',
    better: 'higher',
    match: 60,
    partial: 32,
    format: (v) => String(v),
    about: 'A 256-bit digest of which byte trigrams are common in a file, proposed in 2001 to catch near-duplicate spam e-mails — the same message with a few words changed. Later studies found it more prone to false matches than TLSH or ssdeep. Like the other file hashes it reads bytes, not pictures.',
    thresholds: '≥ 60: the files share most of their bytes. 32–59: some. Below 32: unrelated as byte streams (unrelated test images never scored above 31).',
    robust: ['metadata edits', 'small insertions anywhere in the file'],
    weak: ['re-compression', 'resizing', 'anything that changes most bytes'],
    refs: [
      { label: 'Damiani et al., PDCS 2004', url: 'https://spdp.di.unimi.it/papers/pdcs04.pdf' },
      { label: 'nilsimsa (Python reference)', url: 'https://pypi.org/project/nilsimsa/' },
    ],
  },
  {
    id: 'lzjd',
    group: 'fuzzy',
    name: 'LZJD',
    by: 'Lempel-Ziv Jaccard distance · Raff & Nicholas 2017',
    metric: 'share of digest hashes in common (0–1)',
    better: 'higher',
    match: 0.2,
    partial: 0.06,
    format: f3,
    about: 'Cuts each file into the phrases a Lempel–Ziv compressor would build, hashes them, and compares the two sets of phrase hashes by their overlap (Jaccard index). Designed for malware analysis as a faster, more accurate successor to ssdeep.',
    thresholds: '≥ 0.20: the files share a large part of their bytes. 0.06–0.20: some (a re-saved JPEG often keeps its headers and tables). Below 0.06: unrelated as byte streams (unrelated test images never exceeded 0.058).',
    robust: ['metadata edits', 'appended or inserted data'],
    weak: ['re-compression', 'resizing', 'large appended blocks such as embedded credentials'],
    refs: [
      { label: 'Raff & Nicholas, KDD 2017', url: 'https://doi.org/10.1145/3097983.3098111' },
      { label: 'pyLZJD (Apache-2.0)', url: 'https://github.com/EdwardRaff/pyLZJD' },
    ],
  },
  // ------------------------------------------------------------ hashes
  {
    id: 'pdq',
    group: 'hash',
    name: 'PDQ',
    by: 'Meta · 256-bit DCT hash',
    metric: 'Hamming distance',
    better: 'lower',
    match: 31,
    partial: 63,
    format: bits(256),
    about:
      'The perceptual hash Meta open-sourced for sharing hashes of harmful content between platforms (alongside Microsoft’s proprietary PhotoDNA). It keeps the signs of 256 low-frequency DCT coefficients of a blurred 64×64 luminance image.',
    thresholds: '≤ 31 bits: match — Meta’s recommended threshold. 32–63: weak similarity. Unrelated images average ~128.',
    robust: ['resizing', 'compression', 'mild colour edits', 'small overlays'],
    weak: ['crops', 'rotations', 'mirroring (see next row)'],
    refs: [
      { label: 'PDQ white paper', url: 'https://github.com/facebook/ThreatExchange/blob/main/hashing/hashing.pdf' },
      { label: 'Reference code', url: 'https://github.com/facebook/ThreatExchange/tree/main/pdq' },
    ],
  },
  {
    id: 'pdqDihedral',
    group: 'hash',
    name: 'PDQ + rotations/mirrors',
    by: 'Meta · 8 dihedral variants',
    metric: 'smallest Hamming distance over 8 orientations',
    better: 'lower',
    match: 31,
    partial: 63,
    format: bits(256),
    about:
      'PDQ can cheaply derive the hashes of an image rotated by 90°/180°/270° or mirrored. Comparing against all eight orientations defeats the simplest evasion trick: flipping the image.',
    thresholds: 'Same as PDQ (≤ 31 bits: match).',
    robust: ['90° rotations', 'mirroring', 'plus everything PDQ tolerates'],
    weak: ['crops', 'arbitrary-angle rotation'],
    refs: [{ label: 'Reference code', url: 'https://github.com/facebook/ThreatExchange/tree/main/pdq' }],
  },
  {
    id: 'phash',
    group: 'hash',
    name: 'pHash',
    by: 'DCT perceptual hash · imagehash',
    metric: 'Hamming distance',
    ...HASH64,
    about: 'Shrinks the image to 32×32 grey, takes the discrete cosine transform and records whether each of the 64 lowest frequencies is above the median.',
    thresholds: '≤ 8 bits: match. 9–14: possible. Unrelated images average ~32.',
    robust: ['resizing', 'compression', 'brightness/contrast'],
    weak: ['crops', 'rotations', 'mirroring'],
    refs: [{ label: 'Krawetz, “Looks Like It”', url: 'https://www.hackerfactor.com/blog/index.php?/archives/432-Looks-Like-It.html' }],
  },
  {
    id: 'dhash',
    group: 'hash',
    name: 'dHash',
    by: 'difference hash · imagehash',
    metric: 'Hamming distance',
    ...HASH64,
    about: 'Shrinks to 9×8 grey and records whether each pixel is brighter than its right-hand neighbour, i.e. the direction of horizontal gradients.',
    thresholds: '≤ 8 bits: match. 9–14: possible.',
    robust: ['resizing', 'compression', 'brightness/contrast'],
    weak: ['crops', 'rotations', 'mirroring'],
    refs: [{ label: 'Krawetz, “Kind of Like That”', url: 'https://www.hackerfactor.com/blog/index.php?/archives/529-Kind-of-Like-That.html' }],
  },
  {
    id: 'ahash',
    group: 'hash',
    name: 'aHash',
    by: 'average hash · imagehash',
    metric: 'Hamming distance',
    ...HASH64,
    about: 'The simplest perceptual hash: shrink to 8×8 grey and record which pixels are brighter than the mean.',
    thresholds: '≤ 8 bits: match. 9–14: possible.',
    robust: ['resizing', 'compression'],
    weak: ['crops', 'rotations', 'large dark/bright overlays', 'gamma changes'],
    refs: [{ label: 'imagehash', url: 'https://github.com/JohannesBuchner/imagehash' }],
  },
  {
    id: 'whash',
    group: 'hash',
    name: 'wHash',
    by: 'Haar wavelet hash · imagehash',
    metric: 'Hamming distance',
    ...HASH64,
    about: 'Uses a Haar wavelet decomposition instead of a DCT: compares the 8×8 low-frequency wavelet coefficients (after removing the overall brightness) with their median.',
    thresholds: '≤ 8 bits: match. 9–14: possible.',
    robust: ['resizing', 'compression', 'brightness'],
    weak: ['crops', 'rotations', 'mirroring'],
    refs: [{ label: 'imagehash', url: 'https://github.com/JohannesBuchner/imagehash' }],
  },
  {
    id: 'blockhash',
    group: 'hash',
    name: 'Blockhash',
    by: 'block mean value hash · blockhash.io',
    metric: 'Hamming distance',
    better: 'lower',
    match: 24,
    partial: 48,
    format: bits(256),
    about: 'Splits the image into a 16×16 grid and records, band by band, whether each block is brighter than the band median (Yang, Gu & Niu 2006). Popularised by the Commons Machinery project for matching images to Wikimedia Commons.',
    thresholds: '≤ 24 bits: match. 25–48: possible. Unrelated images average ~128.',
    robust: ['resizing', 'compression', 'colour edits'],
    weak: ['crops', 'rotations', 'mirroring'],
    refs: [{ label: 'blockhash.io', url: 'https://github.com/commonsmachinery/blockhash-js' }],
  },
  {
    id: 'phashSimple',
    group: 'hash',
    name: 'pHash (simple)',
    by: 'row-wise DCT hash · imagehash',
    metric: 'Hamming distance',
    better: 'lower',
    match: 12,
    partial: 19,
    format: bits(64),
    about: 'A lighter variant of pHash: it takes the cosine transform of each row of the 32×32 thumbnail rather than of the whole square, and compares 64 low frequencies with their mean instead of their median.',
    thresholds: '≤ 12 bits: match. 13–19: possible. (Set so that 1% and 5% of unrelated test pairs pass.)',
    robust: ['resizing', 'compression', 'brightness/contrast'],
    weak: ['crops', 'rotations', 'mirroring'],
    refs: [{ label: 'imagehash', url: 'https://github.com/JohannesBuchner/imagehash' }],
  },
  {
    id: 'dhashVertical',
    group: 'hash',
    name: 'dHash (vertical)',
    by: 'difference hash down the columns · imagehash',
    metric: 'Hamming distance',
    better: 'lower',
    match: 20,
    partial: 23,
    format: bits(64),
    about: 'dHash turned on its side: each pixel of an 8×9 thumbnail is compared with the one above it, so it records horizontal edges where ordinary dHash records vertical ones. Many tools run both directions together.',
    thresholds: '≤ 20 bits: match. 21–23: possible. (1% and 5% of unrelated test pairs pass.)',
    robust: ['resizing', 'compression', 'brightness/contrast', 'mirroring (left–right)'],
    weak: ['crops', 'rotations', 'vertical flips'],
    refs: [{ label: 'Krawetz, “Kind of Like That”', url: 'https://www.hackerfactor.com/blog/index.php?/archives/529-Kind-of-Like-That.html' }],
  },
  {
    id: 'whashDb4',
    group: 'hash',
    name: 'wHash (Daubechies)',
    by: 'Daubechies-4 wavelet hash · imagehash',
    metric: 'Hamming distance',
    better: 'lower',
    match: 43,
    partial: 53,
    format: bits(196),
    about: 'The wavelet hash with smoother Daubechies wavelets in place of Haar ones. Their wider filters spill over the edges, so the low-frequency band ends up 14×14: a 196-bit fingerprint of the image’s broad light and dark masses.',
    thresholds: '≤ 43 bits: match. 44–53: possible. (1% and 5% of unrelated test pairs pass.)',
    robust: ['compression', 'brightness', 'colour edits', 'blur'],
    weak: ['crops', 'rotations', 'mirroring', 'large size differences'],
    refs: [
      { label: 'imagehash', url: 'https://github.com/JohannesBuchner/imagehash' },
      { label: 'Daubechies, Ten Lectures on Wavelets (1992)', url: 'https://doi.org/10.1137/1.9781611970104' },
    ],
  },
  {
    id: 'colorhash',
    group: 'hash',
    name: 'Colour hash',
    by: 'share of black, grey and coloured pixels · imagehash',
    metric: 'Hamming distance',
    better: 'lower',
    match: -1,
    partial: 0,
    format: bits(42),
    about: 'Records how much of the image is black, how much grey, and how much faintly or brightly coloured in each of six hue bands — fourteen proportions of 3 bits each. It knows nothing about shapes or layout, only the colour make-up.',
    thresholds: '0 bits: the same colour make-up, shown as partial at most — 16% of unrelated test pairs (any two black-and-white photos, for example) also score 0. Anything above 0 means the colour make-up differs, which can rule a straight copy out but never in.',
    robust: ['crops', 'rotation', 'mirroring', 'resizing'],
    weak: ['any colour edit', 'unrelated images with similar colours'],
    refs: [{ label: 'imagehash', url: 'https://github.com/JohannesBuchner/imagehash' }],
  },
  {
    id: 'cropResistant',
    group: 'hash',
    name: 'Crop-resistant hash',
    by: 'segment-wise dHash · Steinebach, Liu & Yannikos 2014',
    metric: 'share of segments with a twin in the other image',
    better: 'higher',
    match: 0.51,
    partial: 0.2,
    format: (v) => `${Math.round(v * 100)}% of segments`,
    about:
      'Cuts a blurred thumbnail into bright “hills” and dark “valleys”, then hashes the part of the picture under each one separately. Cropping, or pasting the image into a larger one, leaves many segments whole, so their hashes still find each other when whole-image hashes no longer do.',
    thresholds: 'More than half of each image’s segments have a twin in the other (within 16 of 64 bits): match — no unrelated test pair got there. At least a fifth: partial.',
    robust: ['moderate crops', 'compression', 'brightness'],
    weak: ['rotations', 'mirroring', 'heavy colour or contrast edits'],
    refs: [
      { label: 'Steinebach, Liu & Yannikos, ARES 2014', url: 'https://doi.org/10.1109/ARES.2014.85' },
      { label: 'imagehash', url: 'https://github.com/JohannesBuchner/imagehash' },
    ],
  },
  {
    id: 'blockMean0',
    group: 'hash',
    name: 'Block mean hash',
    by: 'OpenCV img_hash · Yang, Gu & Niu 2006',
    metric: 'Hamming distance',
    better: 'lower',
    match: 69,
    partial: 94,
    format: bits(256),
    about: 'OpenCV’s take on the block-mean idea behind Blockhash: shrink to 256×256 grey, average each 16×16 block, and record whether each block is brighter than the image as a whole.',
    thresholds: '≤ 69 bits: match. 70–94: possible. (1% and 5% of unrelated test pairs pass.)',
    robust: ['resizing', 'compression', 'colour edits'],
    weak: ['crops', 'rotations', 'mirroring'],
    refs: [
      { label: 'Yang, Gu & Niu, IIH-MSP 2006', url: 'https://doi.org/10.1109/IIH-MSP.2006.265125' },
      { label: 'OpenCV img_hash', url: 'https://docs.opencv.org/4.x/d4/d93/group__img__hash.html' },
    ],
  },
  {
    id: 'blockMean1',
    group: 'hash',
    name: 'Block mean hash (overlapping)',
    by: 'OpenCV img_hash · mode 1',
    metric: 'Hamming distance',
    better: 'lower',
    match: 260,
    partial: 355,
    format: bits(961),
    about: 'The same hash with blocks that overlap by half, so the 256×256 image yields 31×31 = 961 bits. The finer grid notices smaller changes at the cost of a longer fingerprint.',
    thresholds: '≤ 260 bits: match. 261–355: possible. (1% and 5% of unrelated test pairs pass.)',
    robust: ['resizing', 'compression', 'colour edits'],
    weak: ['crops', 'rotations', 'mirroring'],
    refs: [{ label: 'OpenCV img_hash', url: 'https://docs.opencv.org/4.x/d4/d93/group__img__hash.html' }],
  },
  {
    id: 'marrHildreth',
    group: 'hash',
    name: 'Marr–Hildreth hash',
    by: 'OpenCV img_hash · pHash’s “MH” hash (Zauner 2010)',
    metric: 'Hamming distance',
    better: 'lower',
    match: 216,
    partial: 255,
    format: bits(576),
    about:
      'Equalises the contrast, filters the image with a Marr–Hildreth (Laplacian-of-Gaussian) kernel that responds to edges and blobs, sums the response over 16×16 blocks, and records for 64 neighbourhoods which of their 3×3 blocks respond more than average: 576 bits about where the structure is.',
    thresholds: '≤ 216 bits: match. 217–255: possible. (1% and 5% of unrelated test pairs pass; unrelated images differ in about half the bits.)',
    robust: ['compression', 'brightness/contrast', 'colour edits', 'captions and small overlays'],
    weak: ['crops', 'rotations', 'mirroring'],
    refs: [
      { label: 'Zauner, perceptual hash benchmark (2010)', url: 'https://www.phash.org/docs/pubs/thesis_zauner.pdf' },
      { label: 'OpenCV img_hash', url: 'https://docs.opencv.org/4.x/d4/d93/group__img__hash.html' },
    ],
  },
  {
    id: 'radialVariance',
    group: 'hash',
    name: 'Radial variance hash',
    by: 'OpenCV img_hash · pHash’s radial hash (De Roover et al. 2005)',
    metric: 'peak correlation of the two profiles',
    better: 'higher',
    match: 0.83,
    partial: 0.67,
    format: f3,
    about: 'Measures how much the brightness varies along 180 lines through the centre of the image, one per degree, and keeps 40 frequency coefficients of that profile. Two profiles are compared by correlation, as pHash does.',
    thresholds: '≥ 0.83: match. 0.67–0.83: possible. (1% and 5% of unrelated test pairs pass.)',
    robust: ['compression', 'brightness/contrast', 'blur', 'noise'],
    weak: ['crops that move the centre', 'overlays', 'rotations'],
    refs: [
      { label: 'De Roover et al., IEEE Trans. Signal Processing 2005', url: 'https://doi.org/10.1109/TSP.2005.855414' },
      { label: 'OpenCV img_hash', url: 'https://docs.opencv.org/4.x/d4/d93/group__img__hash.html' },
    ],
  },
  {
    id: 'colorMoment',
    group: 'hash',
    name: 'Colour moment hash',
    by: 'OpenCV img_hash · after Tang et al.',
    metric: 'distance between 42 moment invariants (×10⁴)',
    better: 'lower',
    match: 0.31,
    partial: 2.6,
    format: f2,
    about:
      'Describes each colour channel (in two colour spaces) by its seven Hu moments — statistics of how its brightness is spread that do not change when the picture is rotated, scaled or mirrored. It is the one hash here that shrugs off a flip or a quarter turn, but it sees distributions rather than content.',
    thresholds: '≤ 0.31: match. 0.31–2.6: possible. (1% and 5% of unrelated test pairs pass.)',
    robust: ['mirroring', '90° rotations', 'resizing'],
    weak: ['crops', 'overlays', 'contrast changes', 'unrelated images with similar statistics'],
    refs: [
      { label: 'OpenCV img_hash (after Tang et al., “Perceptual Hashing for Color Images Using Invariant Moments”)', url: 'https://docs.opencv.org/4.x/d4/d93/group__img__hash.html' },
      { label: 'Hu, Visual pattern recognition by moment invariants (1962)', url: 'https://doi.org/10.1109/TIT.1962.1057692' },
    ],
  },

  // ------------------------------------------------------------ geometry
  {
    id: 'orb',
    group: 'geometry',
    name: 'ORB keypoints + RANSAC',
    by: 'OpenCV · Rublee et al. 2011',
    metric: 'geometrically consistent matches (inliers)',
    better: 'higher',
    match: 20,
    partial: 10,
    format: (v) => `${v} inliers`,
    about: 'Finds up to 3,000 corner features per image, matches their binary descriptors (Lowe ratio test), then uses RANSAC to find the largest set of matches explained by a single homography.',
    thresholds: '≥ 20 inliers (and ≥ 50% of matches) with a plausible transform: shared content. 10–19: partial. Unrelated pairs usually give < 10.',
    robust: ['crops', 'rotation', 'scaling', 'compression', 'colour edits', 'overlays'],
    weak: ['mirroring', 'heavy blur', 'flat or repetitive images'],
    refs: [{ label: 'Rublee et al., ICCV 2011', url: 'https://doi.org/10.1109/ICCV.2011.6126544' }],
  },
  {
    id: 'akaze',
    group: 'geometry',
    name: 'AKAZE keypoints + RANSAC',
    by: 'OpenCV · Alcantarilla et al. 2013',
    metric: 'geometrically consistent matches (inliers)',
    better: 'higher',
    match: 20,
    partial: 10,
    format: (v) => `${v} inliers`,
    about: 'Detects blob-like features in a nonlinear scale space, which preserves object edges; scale- and rotation-invariant with binary descriptors.',
    thresholds: 'Same as ORB.',
    robust: ['crops', 'rotation', 'scaling', 'compression', 'blur'],
    weak: ['mirroring', 'flat images'],
    refs: [{ label: 'Alcantarilla et al., BMVC 2013', url: 'https://doi.org/10.5244/C.27.13' }],
  },
  {
    id: 'brisk',
    group: 'geometry',
    name: 'BRISK keypoints + RANSAC',
    by: 'OpenCV · Leutenegger et al. 2011',
    metric: 'geometrically consistent matches (inliers)',
    better: 'higher',
    match: 20,
    partial: 10,
    format: (v) => `${v} inliers`,
    about: 'Scale-space corner detector with a binary descriptor built from brightness comparisons on a circular sampling pattern.',
    thresholds: 'Same as ORB.',
    robust: ['crops', 'rotation', 'scaling', 'compression'],
    weak: ['mirroring', 'blur', 'flat images'],
    refs: [{ label: 'Leutenegger et al., ICCV 2011', url: 'https://doi.org/10.1109/ICCV.2011.6126542' }],
  },
  {
    id: 'xfeat',
    group: 'geometry',
    name: 'XFeat learned keypoints + RANSAC',
    by: 'Potje et al., CVPR 2024 · mutual nearest neighbours',
    metric: 'geometrically consistent matches (inliers)',
    better: 'higher',
    match: 20,
    partial: 10,
    format: (v) => `${v} inliers`,
    model: 'xfeat',
    about:
      'A small neural network trained to find and describe keypoints that survive changes of lighting, blur and viewpoint — far more robust than the hand-made ORB, AKAZE and BRISK detectors on heavily edited copies. Matches are mutual nearest neighbours of the 64-d descriptors, kept only if one homography explains them. The best transform from any detector is used to line B up with A elsewhere on the page.',
    thresholds: 'Same as ORB: ≥ 20 inliers in one plausible transform is a match.',
    robust: ['crops', 'scaling', 'recolouring', 'blur', 'captions and overlays', 'moderate rotation and perspective'],
    weak: ['rotations beyond ~45° (ORB covers those)', 'mirroring (retried with B flipped)'],
    refs: [
      { label: 'Potje et al., CVPR 2024', url: 'https://arxiv.org/abs/2404.19174' },
      { label: 'Code & weights (Apache-2.0)', url: 'https://github.com/verlab/accelerated_features' },
    ],
  },
  {
    id: 'kaze',
    group: 'geometry',
    name: 'KAZE keypoints + RANSAC',
    by: 'OpenCV · Alcantarilla, Bartoli & Davison 2012',
    metric: 'geometrically consistent matches (inliers)',
    better: 'higher',
    match: 20,
    partial: 10,
    format: (v) => `${v} inliers`,
    about:
      'Finds blob-like keypoints in a “nonlinear scale space” — blurring that smooths flat areas but keeps edges sharp — and describes each with 64 numbers. Slower than ORB and AKAZE but often more precise: on the benchmark it found 71% of the edited copies, rotated ones included, with no false matches.',
    thresholds: '≥ 20 inliers (and ≥ 50% of matches) with a plausible transform: shared content. 10–19: partial. Unrelated pairs usually give < 10.',
    robust: ['crops', 'rotation', 'scaling', 'compression', 'colour edits', 'overlays'],
    weak: ['mirroring', 'heavy blur', 'flat or repetitive images'],
    refs: [{ label: 'Alcantarilla, Bartoli & Davison, ECCV 2012', url: 'https://doi.org/10.1007/978-3-642-33783-3_16' }],
    pipeline: 'Grey image fitted inside 512 px; OpenCV KAZE defaults; Lowe ratio 0.8; RANSAC homography (5 px).',
  },
  {
    id: 'fourierMellin',
    group: 'geometry',
    name: 'Fourier–Mellin (rotation & scale)',
    by: 'Reddy & Chatterji 1996 · log-polar phase correlation',
    metric: 'phase-correlation response of the log-polar spectra',
    better: 'higher',
    match: 0.26,
    partial: 0.19,
    format: f3,
    about:
      'Takes each picture’s frequency spectrum — which stays the same when the picture is shifted — and unrolls it in log-polar coordinates, where rotating and resizing the picture become plain shifts that phase correlation can find. So it recognises copies that were moved, turned or rescaled, without finding any keypoints.',
    thresholds: '≥ 0.26: match. 0.19–0.26: partial. (1% and 5% of unrelated test pairs pass.)',
    robust: ['rotation', 'scaling', 'shifts', 'moderate crops', 'compression', 'colour edits'],
    weak: ['mirroring', 'overlays and collages', 'perspective'],
    refs: [{ label: 'Reddy & Chatterji, IEEE TIP 1996', url: 'https://doi.org/10.1109/83.506761' }],
    pipeline: 'Grey, letterboxed into 128×128; Hanning window; amplitude spectrum with Reddy & Chatterji’s high-pass; log-polar warp (OpenCV warpPolar); phase correlation.',
  },
  {
    id: 'phaseCorr',
    group: 'geometry',
    name: 'Phase correlation',
    by: 'Kuglin & Hines 1975 · as OpenCV phaseCorrelate',
    metric: 'share of correlation energy at the best shift',
    better: 'higher',
    match: 0.12,
    partial: 0.083,
    format: f3,
    about:
      'Compares the two pictures’ Fourier transforms to find the one shift that lines them up. If one is a shifted (or unshifted) copy of the other, the correlation piles up at a single point; for unrelated pictures it is spread thin. The workhorse of image registration in astronomy, microscopy and video stabilisation.',
    thresholds: '≥ 0.12: match. 0.083–0.12: partial. (1% and 5% of unrelated test pairs pass.)',
    robust: ['shifts', 'brightness and contrast', 'compression', 'noise', 'colour edits'],
    weak: ['rotation', 'rescaled crops', 'mirroring'],
    refs: [{ label: 'OpenCV phaseCorrelate', url: 'https://docs.opencv.org/4.x/d7/df3/group__imgproc__motion.html' }],
    pipeline: 'Grey pair fitted inside 256 px (B stretched to A’s shape); Hanning window; normalised cross-power spectrum; response in the 5×5 window around the peak.',
  },
  {
    id: 'msTemplate',
    group: 'geometry',
    name: 'Multi-scale template search',
    by: 'normalised cross-correlation at 16 scales · OpenCV matchTemplate',
    metric: 'best normalised cross-correlation',
    better: 'higher',
    match: 0.88,
    partial: 0.79,
    format: f3,
    about:
      'Shrinks each image step by step, down to a quarter of the size at which it fits inside the other, and slides it over the other image looking for the place and size where the pixels agree best. It finds a copy that was cut out and resized, or pasted into a larger picture.',
    thresholds: '≥ 0.88: match. 0.79–0.88: partial. (1% and 5% of unrelated test pairs pass.)',
    robust: ['resized crops', 'pasting into a larger picture', 'compression', 'brightness'],
    weak: ['rotation', 'mirroring', 'perspective'],
    refs: [{ label: 'OpenCV matchTemplate', url: 'https://docs.opencv.org/4.x/df/dfb/group__imgproc__object.html' }],
  },
  {
    id: 'alignedSsim',
    group: 'geometry',
    name: 'SSIM after alignment',
    by: 'homography warp + SSIM',
    metric: 'SSIM over the overlapping region',
    better: 'higher',
    match: 0.8,
    partial: 0.5,
    format: f3,
    about:
      'Uses the best keypoint transform to warp B onto A, then measures SSIM only where they overlap. Shows how much of the disagreement in plain SSIM was just misalignment (crop, rotation, scale).',
    thresholds: 'Same as SSIM. Not applicable when no consistent transform was found.',
    robust: ['crops', 'rotation', 'scaling'],
    weak: ['needs a keypoint match first'],
    refs: [],
  },

  // ------------------------------------------------------------ structure
  {
    id: 'ssim',
    group: 'structure',
    name: 'SSIM',
    by: 'Wang et al. 2004 · structural similarity',
    metric: 'mean SSIM (1 = identical)',
    better: 'higher',
    match: 0.8,
    partial: 0.57,
    format: f3,
    about:
      'Compares local luminance, contrast and structure in 11×11 Gaussian windows and averages the result. The most widely used full-reference image quality metric.',
    thresholds: '≥ 0.80: same image with mild distortion. 0.57–0.80: noticeably altered (the lower line lets through 5% of unrelated test pairs; the common rule of thumb, 0.50, let through 9%). Below: different or misaligned (unrelated photos ≈ 0.1–0.3).',
    robust: ['compression', 'uniform brightness shifts', 'colour changes (luma only)'],
    weak: ['any misalignment: crops, rotations, flips'],
    refs: [{ label: 'Wang et al., IEEE TIP 2004', url: 'https://doi.org/10.1109/TIP.2003.819861' }],
  },
  {
    id: 'msssim',
    group: 'structure',
    name: 'MS-SSIM',
    by: 'Wang, Simoncelli & Bovik 2003',
    metric: 'multi-scale SSIM (1 = identical)',
    better: 'higher',
    match: 0.85,
    partial: 0.6,
    format: f3,
    about: 'SSIM evaluated at five successively halved resolutions and combined, so coarse structure counts as well as fine detail. Less sensitive to noise and blur than SSIM.',
    thresholds: '≥ 0.85: same image. 0.60–0.85: altered. Below 0.60: different or misaligned.',
    robust: ['compression', 'noise', 'blur'],
    weak: ['misalignment'],
    refs: [{ label: 'Wang et al., Asilomar 2003', url: 'https://doi.org/10.1109/ACSSC.2003.1292216' }],
  },
  {
    id: 'psnr',
    group: 'structure',
    name: 'PSNR',
    by: 'peak signal-to-noise ratio',
    metric: 'decibels (∞ = identical)',
    better: 'higher',
    match: 28,
    partial: 20,
    format: (v) => (v === Infinity ? '∞ dB' : `${v.toFixed(1)} dB`),
    about: 'Mean squared error between pixel values expressed on a log scale. Simple and standard for compression, but it treats every pixel difference the same, regardless of how visible it is.',
    thresholds: '≥ 28 dB: near-identical (typical of JPEG compression). 20–28 dB: visibly altered. Below 20 dB: different, or a global brightness/colour change.',
    robust: ['mild compression'],
    weak: ['brightness or colour shifts', 'misalignment'],
    refs: [],
  },
  {
    id: 'ncc',
    group: 'structure',
    name: 'Normalised cross-correlation',
    by: 'Pearson correlation of brightness',
    metric: 'correlation (1 = identical pattern)',
    better: 'higher',
    match: 0.9,
    partial: 0.7,
    format: f3,
    about: 'Correlates the brightness of corresponding pixels after removing each image’s mean and contrast, so uniform brightness/contrast changes do not matter.',
    thresholds: '≥ 0.90: match. 0.70–0.90: partial. Below 0.70: different or misaligned.',
    robust: ['brightness', 'contrast', 'compression'],
    weak: ['misalignment', 'local edits'],
    refs: [],
  },
  {
    id: 'uqi',
    group: 'structure',
    name: 'Universal Quality Index',
    by: 'Wang & Bovik 2002',
    metric: 'mean Q over 8×8 windows (1 = identical)',
    better: 'higher',
    match: 0.7,
    partial: 0.4,
    format: f3,
    about: 'The predecessor of SSIM: combines correlation, luminance distortion and contrast distortion in sliding 8×8 windows, without SSIM’s stabilising constants.',
    thresholds: '≥ 0.70: match. 0.40–0.70: partial. Below 0.40: different.',
    robust: ['compression', 'colour (grey only)'],
    weak: ['misalignment', 'noise'],
    refs: [{ label: 'Wang & Bovik, IEEE SPL 2002', url: 'https://doi.org/10.1109/97.995823' }],
  },
  {
    id: 'gmsd',
    group: 'structure',
    name: 'GMSD',
    by: 'Xue et al. 2014 · gradient similarity',
    metric: 'gradient magnitude similarity deviation (0 = identical)',
    better: 'lower',
    match: 0.1,
    partial: 0.18,
    format: f3,
    about: 'Compares edge strength (gradient magnitude) at every location; the spread of the per-pixel similarity map is the score. Sensitive to new or missing edges such as added text.',
    thresholds: '≤ 0.10: match. 0.10–0.18: partial. Above 0.18: different (unrelated ≈ 0.25–0.35).',
    robust: ['colour changes', 'brightness', 'compression'],
    weak: ['misalignment', 'blur', 'added text/edges'],
    refs: [{ label: 'Xue et al., IEEE TIP 2014', url: 'https://arxiv.org/abs/1308.3052' }],
  },
  {
    id: 'deltaE',
    group: 'structure',
    name: 'CIEDE2000 colour difference',
    by: 'CIE ΔE₀₀ · mean over pixels',
    metric: 'mean ΔE₀₀ (0 = identical colour)',
    better: 'lower',
    match: 5,
    partial: 12,
    format: (v) => `ΔE ${v.toFixed(1)}`,
    about: 'Converts both images to CIELAB and measures the perceptual colour difference at every pixel with the CIEDE2000 formula used in print and textile quality control. A ΔE of about 1–2 is the smallest difference people notice.',
    thresholds: '≤ 5: match. 5–12: partial. Above 12: different colours (or misaligned).',
    robust: ['compression', 'blur'],
    weak: ['colour/brightness edits', 'misalignment'],
    refs: [{ label: 'Sharma et al. 2005', url: 'https://doi.org/10.1002/col.20070' }],
  },
  {
    id: 'changed',
    group: 'structure',
    name: 'Changed-pixel ratio',
    by: 'share of pixels with ΔE₀₀ > 5',
    metric: 'fraction of visibly changed pixels',
    better: 'lower',
    match: 0.1,
    partial: 0.4,
    format: pct,
    about: 'The fraction of locations whose colour changed by more than ΔE₀₀ 5 — a plain-language answer to “how much of the picture was altered?”.',
    thresholds: '≤ 10% changed: match. 10–40%: partial. More than 40%: different.',
    robust: ['compression', 'small local edits'],
    weak: ['global colour edits', 'misalignment'],
    refs: [],
  },
  {
    id: 'carlini',
    group: 'structure',
    name: 'Tiled ℓ2 extraction test',
    by: 'Carlini et al. 2023 · max over 16 tiles',
    metric: 'largest per-tile RMS pixel difference (0–1)',
    better: 'lower',
    match: 0.15,
    partial: null,
    format: f3,
    about:
      'The test Carlini et al. used to decide that Stable Diffusion had regurgitated a training image: resize both images to 512×512, cut each into 16 tiles, and take the worst tile’s root-mean-square difference. Because it is the worst tile that counts, a near-copy with one changed corner fails, which keeps the test strict — it flags near-verbatim reproductions, not loose resemblance.',
    thresholds: '≤ 0.15: “extracted” — a near-verbatim reproduction in Carlini et al.’s sense. Above 0.15: not extracted (which says nothing about looser copying).',
    robust: ['compression', 'tiny colour shifts'],
    weak: ['any crop, shift, flip or rotation (needs pixel alignment)', 'a local edit in any one tile'],
    refs: [{ label: 'Carlini et al., Extracting Training Data from Diffusion Models (USENIX Security 2023)', url: 'https://arxiv.org/abs/2301.13188' }],
    pipeline: 'Both images resized to 512×512 (bilinear), 16 non-overlapping 128×128 tiles, RMS difference over RGB in [0, 1], maximum over tiles.',
  },

  {
    id: 'fsim',
    group: 'structure',
    name: 'FSIM (feature similarity)',
    by: 'Zhang, Zhang, Mou & Zhang 2011 · phase congruency',
    metric: 'similarity 0–1',
    better: 'higher',
    match: 0.76,
    partial: 0.67,
    format: f3,
    about:
      'Finds the features people notice — places where the picture’s frequency components line up in phase (“phase congruency”) — and compares those, the gradients and the colours point by point. One of the classic measures that agree best with people’s judgements of image quality.',
    thresholds: '≥ 0.76: match. 0.67–0.76: partial. (1% and 5% of unrelated test pairs pass.)',
    robust: ['compression', 'colour and brightness changes', 'noise', 'captions and overlays'],
    weak: ['crops and shifts', 'rotation', 'mirroring', 'blur'],
    refs: [{ label: 'Zhang et al., IEEE TIP 2011', url: 'https://doi.org/10.1109/TIP.2011.2109730' }],
  },
  {
    id: 'vsi',
    group: 'structure',
    name: 'VSI (saliency-weighted)',
    by: 'Zhang, Shen & Li 2014 · visual saliency',
    metric: 'similarity 0–1',
    better: 'higher',
    match: 0.86,
    partial: 0.83,
    format: f3,
    about: 'Predicts where a viewer’s eye would go (a saliency map) and compares saliency, gradients and colour point by point, counting differences more where people look.',
    thresholds: '≥ 0.86: match. 0.83–0.86: partial. (1% and 5% of unrelated test pairs pass.)',
    robust: ['compression', 'colour edits', 'noise', 'contrast'],
    weak: ['crops and shifts', 'rotation', 'mirroring'],
    refs: [{ label: 'Zhang, Shen & Li, IEEE TIP 2014', url: 'https://doi.org/10.1109/TIP.2014.2346028' }],
  },
  {
    id: 'haarpsi',
    group: 'structure',
    name: 'HaarPSI',
    by: 'Reisenhofer, Bosse, Kutyniok & Wiegand 2018 · Haar wavelets',
    metric: 'similarity 0–1',
    better: 'higher',
    match: 0.37,
    partial: 0.25,
    format: f3,
    about: 'Compares the two pictures’ edges at three scales using the simplest wavelets there are (Haar), weighting each spot by how much structure it holds. Despite its simplicity it ranks among the best predictors of human quality ratings.',
    thresholds: '≥ 0.37: match. 0.25–0.37: partial. (1% and 5% of unrelated test pairs pass.)',
    robust: ['compression', 'colour edits', 'noise', 'blur', 'contrast'],
    weak: ['crops and shifts', 'rotation', 'mirroring', 'overlays'],
    refs: [{ label: 'Reisenhofer et al., Signal Process. Image Commun. 2018', url: 'https://doi.org/10.1016/j.image.2017.11.001' }],
  },
  {
    id: 'vif',
    group: 'structure',
    name: 'Visual information fidelity (VIF)',
    by: 'Sheikh & Bovik 2006 · pixel domain',
    metric: 'share of A’s visual information that survives in B',
    better: 'higher',
    match: 0.078,
    partial: 0.047,
    format: f3,
    about:
      'Treats viewing as a noisy channel and asks how much of the information A sends to the eye still arrives through B — an information-theory view of quality that later became one ingredient of Netflix’s VMAF. 1 means B carries everything A did; it can exceed 1 when B has more contrast.',
    thresholds: '≥ 0.078: match. 0.047–0.078: partial. (1% and 5% of unrelated test pairs pass; even a heavily compressed copy keeps far more than that.)',
    robust: ['compression', 'colour edits', 'noise', 'contrast', 'overlays'],
    weak: ['crops and shifts', 'rotation', 'mirroring'],
    refs: [{ label: 'Sheikh & Bovik, IEEE TIP 2006', url: 'https://doi.org/10.1109/TIP.2005.859378' }],
  },
  {
    id: 'nmi',
    group: 'structure',
    name: 'Normalised mutual information',
    by: 'Studholme, Hill & Hawkes 1999 · as scikit-image',
    metric: 'from 1 (independent) to 2 (one determines the other)',
    better: 'higher',
    match: 1.1,
    partial: 1.07,
    format: f3,
    about: 'How well one picture’s brightness at each point predicts the other’s, from information theory. It does not care how tones were remapped — inverted, recoloured or re-curved — only whether they move together, which is why it is the standard way to align medical scans taken on different machines.',
    thresholds: '≥ 1.10: match. 1.07–1.10: partial. (1% and 5% of unrelated test pairs pass.)',
    robust: ['any tone or colour remapping', 'inversion', 'compression', 'noise'],
    weak: ['crops and shifts', 'rotation', 'mirroring'],
    refs: [
      { label: 'Studholme, Hill & Hawkes, Pattern Recognit. 1999', url: 'https://doi.org/10.1016/S0031-3203(98)00091-0' },
      { label: 'scikit-image', url: 'https://scikit-image.org/docs/stable/api/skimage.metrics.html' },
    ],
  },
  {
    id: 'dss',
    group: 'structure',
    name: 'DSS (DCT subbands)',
    by: 'Balanov, Schwartz, Moshe & Peleg 2015',
    metric: 'similarity 0–1',
    better: 'higher',
    match: 0.35,
    partial: 0.17,
    format: f3,
    about: 'Splits both pictures into the 8×8 frequency blocks JPEG uses and compares them band by band, judging each band by its worst-matching 5% of places — so a change confined to one area counts heavily.',
    thresholds: '≥ 0.35: match. 0.17–0.35: partial. (1% and 5% of unrelated test pairs pass.)',
    robust: ['compression', 'colour edits', 'noise', 'blur'],
    weak: ['crops and shifts', 'rotation', 'mirroring', 'local edits such as captions'],
    refs: [{ label: 'Balanov et al., ICIP 2015', url: 'https://doi.org/10.1109/ICIP.2015.7351172' }],
  },
  {
    id: 'msGmsd',
    group: 'structure',
    name: 'Multi-scale GMSD',
    by: 'Zhang, Sander & Bermak 2017 · four scales',
    metric: 'deviation (0 = identical)',
    better: 'lower',
    match: 0.19,
    partial: 0.26,
    format: f3,
    about: 'Measures how unevenly gradient similarity is spread over the picture at four scales, weighted like the eye’s sensitivity to detail — the multi-scale extension of the GMSD test above.',
    thresholds: '≤ 0.19: match. 0.19–0.26: partial. (1% and 5% of unrelated test pairs pass.)',
    robust: ['compression', 'colour edits', 'noise', 'contrast'],
    weak: ['crops and shifts', 'rotation', 'mirroring', 'overlays'],
    refs: [{ label: 'Zhang, Sander & Bermak, ICASSP 2017', url: 'https://doi.org/10.1109/ICASSP.2017.7952357' }],
  },
  {
    id: 'mdsi',
    group: 'structure',
    name: 'MDSI',
    by: 'Ziaei Nafchi, Shahkolaei, Hedjam & Cheriet 2016',
    metric: 'mean deviation (0 = identical)',
    better: 'lower',
    match: 0.355,
    partial: 0.406,
    format: f3,
    about: 'Combines how alike the gradients and the colours are at each point, then measures how unevenly that similarity is spread: a picture degraded evenly scores better than one damaged in patches. Built to rate image quality; it is one of the weaker copy detectors here.',
    thresholds: '≤ 0.355: match. 0.355–0.406: partial. (1% and 5% of unrelated test pairs pass.)',
    robust: ['compression', 'contrast'],
    weak: ['crops and shifts', 'rotation', 'mirroring', 'colour edits', 'blur'],
    refs: [{ label: 'Ziaei Nafchi et al., IEEE Access 2016', url: 'https://doi.org/10.1109/ACCESS.2016.2604042' }],
  },
  {
    id: 'prattFom',
    group: 'structure',
    name: 'Edge agreement (Pratt’s FOM)',
    by: 'Abdou & Pratt 1979 · Canny edges',
    metric: 'figure of merit (1 = the same edges)',
    better: 'higher',
    match: 0.62,
    partial: 0.45,
    format: f3,
    about:
      'Traces the outlines in each picture with Canny’s edge detector and scores how close every edge of one picture lies to an edge of the other — Pratt’s classic yardstick for edge detectors, used in both directions. It looks at the drawing, not the colours, so it survives recolouring and greyscale but needs the pictures lined up.',
    thresholds: '≥ 0.62: match. 0.45–0.62: partial. (1% and 5% of unrelated test pairs pass.)',
    robust: ['colour and hue changes', 'greyscale', 'brightness and contrast', 'compression'],
    weak: ['crops and shifts', 'blur and pixelation', 'rotation', 'mirroring'],
    refs: [
      { label: 'Abdou & Pratt, Proc. IEEE 1979', url: 'https://doi.org/10.1109/PROC.1979.11325' },
      { label: 'Canny, IEEE TPAMI 1986', url: 'https://doi.org/10.1109/TPAMI.1986.4767851' },
    ],
  },
  {
    id: 'modHausdorff',
    group: 'structure',
    name: 'Edge distance (modified Hausdorff)',
    by: 'Dubuisson & Jain 1994 · Canny edges',
    metric: 'average distance between the two sets of edges',
    better: 'lower',
    match: 3,
    partial: 6.9,
    format: (v) => `${v.toFixed(1)} px`,
    about: 'How far, on average, each outline of one picture lies from the nearest outline of the other, taking the worse of the two directions — the variant Dubuisson and Jain found most dependable among two dozen ways of comparing shapes.',
    thresholds: '≤ 3.0 px: match. 3.0–6.9 px: partial. (1% and 5% of unrelated test pairs pass; distances measured on images fitted inside 512 px.)',
    robust: ['colour and hue changes', 'greyscale', 'brightness', 'compression'],
    weak: ['crops and shifts', 'blur', 'rotation', 'clutter added to one image'],
    refs: [{ label: 'Dubuisson & Jain, ICPR 1994', url: 'https://doi.org/10.1109/ICPR.1994.576361' }],
  },
  {
    id: 'ncd',
    group: 'structure',
    name: 'Compression distance (NCD)',
    by: 'Cilibrasi & Vitányi 2005 · deflate',
    metric: 'normalised compression distance (≈1 = unrelated)',
    better: 'lower',
    match: 0.994,
    partial: 0.999,
    format: f3,
    about:
      'Compresses each picture, then the two together: if the pair compresses to little more than one picture alone, the compressor found the second picture’s information already in the first. A parameter-free “universal” similarity from information theory, used to cluster music, genomes and languages. Unrelated pictures score about 1, and even close copies only a little below.',
    thresholds: '≤ 0.994: match. 0.994–0.999: partial. (1% and 5% of unrelated test pairs pass.) Compressors differ slightly between browsers, so the third decimal can vary.',
    robust: ['colour and hue changes', 'greyscale', 'captions and overlays'],
    weak: ['JPEG noise and grain', 'contrast changes', 'resizing'],
    refs: [
      { label: 'Cilibrasi & Vitányi, IEEE Trans. Inf. Theory 2005', url: 'https://doi.org/10.1109/TIT.2005.844059' },
      { label: 'Li et al., The similarity metric (2004)', url: 'https://doi.org/10.1109/TIT.2004.838101' },
    ],
    pipeline: 'Both images as 128×128 grey bytes; raw deflate (the browser’s CompressionStream, zlib’s default level).',
  },

  // ------------------------------------------------------------ color
  {
    id: 'histCorrel',
    group: 'color',
    name: 'Colour histogram correlation',
    by: 'OpenCV HISTCMP_CORREL · 8×8×8 RGB bins',
    metric: 'correlation (1 = same distribution)',
    better: 'higher',
    match: 0.97,
    partial: 0.72,
    format: f3,
    about:
      'Counts how many pixels fall into each of 512 colour bins and correlates the two counts. OpenCV’s tutorial bins only hue and saturation, but that ignores brightness, so every black-and-white picture looks identical to it (a fifth to a third of unrelated test pairs “matched”); binning red, green and blue avoids that.',
    thresholds: '≥ 0.97: match. 0.72–0.97: partial. (1% and 5% of unrelated test pairs pass.)',
    robust: ['crops', 'rotation', 'mirroring'],
    weak: ['colour and brightness edits', 'unrelated images with similar palettes'],
    refs: [{ label: 'OpenCV tutorial', url: 'https://docs.opencv.org/4.x/d8/dc8/tutorial_histogram_comparison.html' }],
  },
  {
    id: 'histChi',
    group: 'color',
    name: 'χ² histogram distance',
    by: 'symmetric chi-square · 8×8×8 RGB bins',
    metric: 'distance (0 = identical, 1 = disjoint)',
    better: 'lower',
    match: 0.13,
    partial: 0.28,
    format: f3,
    about: 'Sums squared bin differences weighted by bin size, emphasising differences in rare colours.',
    thresholds: '≤ 0.13: match. 0.13–0.28: partial. (1% and 5% of unrelated test pairs pass.)',
    robust: ['crops', 'rotation', 'mirroring'],
    weak: ['colour edits', 'similar palettes'],
    refs: [],
  },
  {
    id: 'histIntersect',
    group: 'color',
    name: 'Colour histogram intersection',
    by: 'Swain & Ballard 1991 · 8×8×8 RGB',
    metric: 'shared mass (1 = identical)',
    better: 'higher',
    match: 0.7,
    partial: 0.55,
    format: f3,
    about: 'The original "colour indexing" idea: the fraction of pixels whose RGB colour bin is shared by both images.',
    thresholds: '≥ 0.70: match. 0.55–0.70: partial. (1% and 5% of unrelated test pairs pass.)',
    robust: ['crops', 'rotation', 'mirroring'],
    weak: ['colour/brightness edits', 'similar palettes'],
    refs: [{ label: 'Swain & Ballard, IJCV 1991', url: 'https://doi.org/10.1007/BF00130487' }],
  },
  {
    id: 'histBhatt',
    group: 'color',
    name: 'Bhattacharyya distance',
    by: 'OpenCV HISTCMP_BHATTACHARYYA · 8×8×8 RGB bins',
    metric: 'distance (0 = identical, 1 = disjoint)',
    better: 'lower',
    match: 0.28,
    partial: 0.44,
    format: f3,
    about: 'Measures the overlap of two probability distributions (here colour histograms); common in object tracking.',
    thresholds: '≤ 0.28: match. 0.28–0.44: partial. (1% and 5% of unrelated test pairs pass.)',
    robust: ['crops', 'rotation', 'mirroring'],
    weak: ['colour edits', 'similar palettes'],
    refs: [],
  },
  {
    id: 'lumaEmd',
    group: 'color',
    name: 'Brightness distribution (EMD)',
    by: 'Earth Mover’s distance · 256 bins',
    metric: 'normalised Wasserstein distance',
    better: 'lower',
    match: 0.02,
    partial: 0.05,
    format: f3,
    about: 'How much "work" it takes to reshape one brightness histogram into the other — small shifts in brightness cost little, unlike bin-by-bin measures.',
    thresholds: '≤ 0.02: match. 0.02–0.05: partial. Above 0.05: different.',
    robust: ['crops', 'rotation', 'mirroring', 'colour hue changes'],
    weak: ['brightness/contrast edits', 'unrelated images with similar tones'],
    refs: [{ label: 'Rubner et al., IJCV 2000', url: 'https://doi.org/10.1023/A:1026543900054' }],
  },
  {
    id: 'klDiv',
    group: 'color',
    name: 'Kullback–Leibler divergence',
    by: 'OpenCV HISTCMP_KL_DIV · 8×8×8 RGB bins',
    metric: 'divergence of A’s colours from B’s (0 = same)',
    better: 'lower',
    match: 0.33,
    partial: 0.8,
    format: f3,
    about: 'Information theory’s measure of how surprised you would be by A’s colours if you expected B’s. It is lopsided — A against B differs from B against A — and harsh on colours one image has and the other lacks.',
    thresholds: '≤ 0.33: match. 0.33–0.80: partial. (1% and 5% of unrelated test pairs pass.)',
    robust: ['crops', 'rotation', 'mirroring'],
    weak: ['colour and brightness edits', 'unrelated images with similar palettes'],
    refs: [
      { label: 'Kullback & Leibler, Ann. Math. Stat. 1951', url: 'https://doi.org/10.1214/aoms/1177729694' },
      { label: 'OpenCV compareHist', url: 'https://docs.opencv.org/4.x/d8/dc8/tutorial_histogram_comparison.html' },
    ],
  },
  {
    id: 'jsDiv',
    group: 'color',
    name: 'Jensen–Shannon distance',
    by: 'symmetric, bounded relative of KL · 8×8×8 RGB bins',
    metric: 'distance in bits (0 = same, 1 = disjoint)',
    better: 'lower',
    match: 0.32,
    partial: 0.49,
    format: f3,
    about: 'Compares each colour histogram with the average of the two, which makes Kullback–Leibler symmetric and bounded; its square root is a true distance. A standard way to compare probability distributions, in image retrieval and in machine-learning evaluation alike.',
    thresholds: '≤ 0.32: match. 0.32–0.49: partial. (1% and 5% of unrelated test pairs pass.)',
    robust: ['crops', 'rotation', 'mirroring'],
    weak: ['colour and brightness edits', 'unrelated images with similar palettes'],
    refs: [
      { label: 'Lin, IEEE Trans. Inf. Theory 1991', url: 'https://doi.org/10.1109/18.61115' },
      { label: 'Endres & Schindelin, IEEE Trans. Inf. Theory 2003', url: 'https://doi.org/10.1109/TIT.2003.813506' },
    ],
  },
  {
    id: 'ksLuma',
    group: 'color',
    name: 'Kolmogorov–Smirnov statistic',
    by: 'two-sample test on brightness',
    metric: 'largest gap between the two brightness distributions',
    better: 'lower',
    match: 0.1,
    partial: 0.2,
    format: f3,
    about: 'The classic statistical test of whether two samples come from the same distribution, applied to the brightness of every pixel: it finds the brightness level at which the share of darker pixels differs most between the two images.',
    thresholds: '≤ 0.10: match. 0.10–0.20: partial. (1% and 5% of unrelated test pairs pass.)',
    robust: ['crops', 'rotation', 'mirroring', 'hue changes'],
    weak: ['brightness and contrast edits', 'unrelated images with similar tones'],
    refs: [
      { label: 'Smirnov, Ann. Math. Stat. 1948', url: 'https://doi.org/10.1214/aoms/1177730256' },
      { label: 'scipy.stats.ks_2samp', url: 'https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.ks_2samp.html' },
    ],
  },
  {
    id: 'hsvMoments',
    group: 'color',
    name: 'Colour moments',
    by: 'Stricker & Orengo 1995 · mean, spread and skew of H, S, V',
    metric: 'summed difference of nine moments',
    better: 'lower',
    match: 0.15,
    partial: 0.28,
    format: f3,
    about: 'Sums up hue, saturation and brightness with three numbers each — average, spread and lopsidedness — and compares the nine numbers. A compact classic of image retrieval: nine numbers say a surprising amount about a picture’s look.',
    thresholds: '≤ 0.15: match. 0.15–0.28: partial. (1% and 5% of unrelated test pairs pass.)',
    robust: ['crops', 'rotation', 'mirroring', 'resizing'],
    weak: ['colour edits', 'overlays', 'unrelated images with a similar look'],
    refs: [{ label: 'Stricker & Orengo, SPIE 1995', url: 'https://doi.org/10.1117/12.205308' }],
  },
  {
    id: 'ccv',
    group: 'color',
    name: 'Colour coherence vectors',
    by: 'Pass, Zabih & Miller 1996 · 64 colours',
    metric: 'difference in clumped and scattered colour (0 = same, 1 = disjoint)',
    better: 'lower',
    match: 0.28,
    partial: 0.42,
    format: f3,
    about: 'Splits the pixels of each colour into those in large connected patches (“coherent”) and those scattered about, so a red ball and a sprinkling of red dots no longer count as the same. Images that share their colours and the way those colours clump score near 0.',
    thresholds: '≤ 0.28: match. 0.28–0.42: partial. (1% and 5% of unrelated test pairs pass.)',
    robust: ['crops', 'mirroring', '90° rotations', 'compression', 'captions'],
    weak: ['colour edits', 'arbitrary rotations', 'heavy restyling'],
    refs: [{ label: 'Pass, Zabih & Miller, ACM Multimedia 1996', url: 'https://doi.org/10.1145/244130.244148' }],
  },
  {
    id: 'correlogram',
    group: 'color',
    name: 'Colour correlogram',
    by: 'Huang et al. 1997 · 64 colours at distances 1, 3, 5, 7',
    metric: 'relative L1 distance',
    better: 'lower',
    match: 1.29,
    partial: 2.13,
    format: f2,
    about: 'For each colour, the chance that a pixel 1, 3, 5 or 7 steps from a pixel of that colour has the same colour. It captures how colours are arranged at small scales — texture — without the images needing to line up.',
    thresholds: '≤ 1.29: match. 1.29–2.13: partial. (1% and 5% of unrelated test pairs pass.)',
    robust: ['crops', 'mirroring', '90° rotations'],
    weak: ['resizing', 'blur and noise', 'colour edits'],
    refs: [{ label: 'Huang et al., CVPR 1997', url: 'https://doi.org/10.1109/CVPR.1997.609412' }],
  },
  {
    id: 'paletteEmd',
    group: 'color',
    name: 'Palette distance (EMD)',
    by: '8 dominant colours · Earth Mover’s Distance',
    metric: 'colour change (ΔE) needed to turn one palette into the other',
    better: 'lower',
    match: 6.1,
    partial: 12.5,
    format: f2,
    about: 'Finds each image’s eight main colours (k-means in CIELAB), then computes the least colour change needed to turn one palette into the other, each colour weighted by how much of the picture it covers. A few ΔE means the same colours in the same proportions.',
    thresholds: '≤ 6.1: match. 6.1–12.5: partial. (1% and 5% of unrelated test pairs pass.)',
    robust: ['crops', 'rotation', 'mirroring', 'resizing', 'compression'],
    weak: ['colour edits', 'overlays that add colour', 'unrelated images with similar palettes'],
    refs: [{ label: 'Rubner, Tomasi & Guibas, IJCV 2000', url: 'https://doi.org/10.1023/A:1026543900054' }],
  },
  {
    id: 'meanColor',
    group: 'color',
    name: 'Average colour',
    by: 'CIEDE2000 between the mean colours',
    metric: 'colour difference ΔE₀₀',
    better: 'lower',
    match: 0.8,
    partial: 5.6,
    format: f2,
    about: 'The average colour of each picture, compared with CIEDE2000, the formula used in printing and paint matching. Under 1 is invisible to most people. Mainly useful to show how little one number can say: very different pictures can share an average.',
    thresholds: '≤ 0.8: match. 0.8–5.6: partial. (1% and 5% of unrelated test pairs pass.)',
    robust: ['crops', 'rotation', 'mirroring', 'resizing'],
    weak: ['any colour edit', 'unrelated images with the same overall tint'],
    refs: [{ label: 'Sharma, Wu & Dalal, Color Res. Appl. 2005', url: 'https://doi.org/10.1002/col.20070' }],
  },

  // ------------------------------------------------------------ texture & shape
  {
    id: 'gist',
    group: 'texture',
    name: 'GIST scene descriptor',
    by: 'Oliva & Torralba 2001 · LMgist, 512 numbers',
    metric: 'Euclidean distance',
    better: 'lower',
    match: 0.37,
    partial: 0.53,
    format: f3,
    about:
      'Sums up the “gist” of a scene — how much structure of each orientation and size sits in each square of a 4×4 grid — the way people take in a scene at a glance. Before deep learning it was the standard tool for finding near-duplicate images among millions (Douze et al. 2009).',
    thresholds: '≤ 0.37: match. 0.37–0.53: partial. (1% and 5% of unrelated test pairs pass.)',
    robust: ['compression', 'colour changes', 'captions and overlays', 'contrast'],
    weak: ['crops', 'rotations', 'mirroring'],
    refs: [
      { label: 'Oliva & Torralba, IJCV 2001', url: 'https://doi.org/10.1023/A:1011139631724' },
      { label: 'Douze et al., CIVR 2009', url: 'https://doi.org/10.1145/1646396.1646421' },
    ],
    pipeline: 'Mean of R, G, B; scaled to cover 256×256 (bilinear) and centre-cropped; LMgist.m defaults: prefilter fc = 4, 8 orientations × 4 scales, 4×4 blocks.',
  },
  {
    id: 'hog',
    group: 'texture',
    name: 'Histogram of oriented gradients',
    by: 'Dalal & Triggs 2005 · 9 orientations, 16-pixel cells',
    metric: 'cosine similarity',
    better: 'higher',
    match: 0.9,
    partial: 0.87,
    format: f3,
    about: 'Divides a 128×128 version of each picture into cells and records which way the edges in each cell run — the descriptor behind classic pedestrian detectors. It captures the layout of edges, so the two images must be framed alike.',
    thresholds: '≥ 0.90: match. 0.87–0.90: partial. (1% and 5% of unrelated test pairs pass.)',
    robust: ['compression', 'colour and brightness changes', 'noise'],
    weak: ['crops', 'rotations', 'mirroring'],
    refs: [{ label: 'Dalal & Triggs, CVPR 2005', url: 'https://doi.org/10.1109/CVPR.2005.177' }],
  },
  {
    id: 'gabor',
    group: 'texture',
    name: 'Gabor texture energy',
    by: 'Manjunath & Ma 1996 · 4 scales × 6 orientations',
    metric: 'mean relative difference of 48 energies',
    better: 'lower',
    match: 0.112,
    partial: 0.149,
    format: f3,
    about: 'Filters the picture with 24 Gabor filters — small striped wave patterns at four sizes and six angles, much like cells in the visual cortex — and compares how strongly each one responds. The basis of the MPEG-7 standard’s texture descriptor.',
    thresholds: '≤ 0.112: match. 0.112–0.149: partial. (1% and 5% of unrelated test pairs pass.)',
    robust: ['compression', 'colour changes', 'mirroring', 'noise'],
    weak: ['blur and pixelation', 'rotations', 'unrelated images with similar texture'],
    refs: [{ label: 'Manjunath & Ma, IEEE TPAMI 1996', url: 'https://doi.org/10.1109/34.531803' }],
  },
  {
    id: 'glcm',
    group: 'texture',
    name: 'Haralick texture (GLCM)',
    by: 'Haralick, Shanmugam & Dinstein 1973 · co-occurrence statistics',
    metric: 'mean relative difference of 12 statistics',
    better: 'lower',
    match: 0.069,
    partial: 0.118,
    format: f3,
    about: 'Counts how often each shade of grey sits next to each other shade, then sums the counts up as contrast, smoothness, uniformity and correlation — the textbook description of texture since 1973, used in medical and satellite imaging.',
    thresholds: '≤ 0.069: match. 0.069–0.118: partial. (1% and 5% of unrelated test pairs pass.)',
    robust: ['crops', 'mirroring', '90° rotations', 'colour changes'],
    weak: ['blur', 'noise', 'contrast edits', 'unrelated images with similar texture'],
    refs: [{ label: 'Haralick, Shanmugam & Dinstein, IEEE SMC 1973', url: 'https://doi.org/10.1109/TSMC.1973.4309314' }],
  },
  {
    id: 'lbp',
    group: 'texture',
    name: 'Local binary patterns',
    by: 'Ojala, Pietikäinen & Mäenpää 2002 · 8 neighbours',
    metric: 'χ² distance between pattern histograms',
    better: 'lower',
    match: 0.005,
    partial: 0.01,
    format: (v) => v.toFixed(4),
    about: 'Codes every pixel by which of its eight neighbours are at least as bright — flat, edge, corner or spot — and compares how often each kind occurs. A staple of texture and face recognition; it describes the grain of a picture rather than what it shows, so it is a weak copy detector.',
    thresholds: '≤ 0.005: match. 0.005–0.010: partial. (1% and 5% of unrelated test pairs pass.) Compression and blur change exactly the fine grain it measures.',
    robust: ['brightness and colour changes', 'mirroring', '90° rotations'],
    weak: ['compression', 'blur and noise', 'resizing'],
    refs: [{ label: 'Ojala, Pietikäinen & Mäenpää, IEEE TPAMI 2002', url: 'https://doi.org/10.1109/TPAMI.2002.1017623' }],
  },
  {
    id: 'zernike',
    group: 'texture',
    name: 'Zernike moments',
    by: 'Teague 1980 · degree 8, 25 magnitudes',
    metric: 'Euclidean distance',
    better: 'lower',
    match: 0.02,
    partial: 0.113,
    format: f3,
    about: 'Describes how brightness is spread around the picture’s centre with 25 numbers that do not change when it is rotated or mirrored — a classic shape descriptor, used for instance to search trademark logos.',
    thresholds: '≤ 0.020: match. 0.020–0.113: partial. (1% and 5% of unrelated test pairs pass.)',
    robust: ['rotation about the centre', 'mirroring', 'resizing', 'compression'],
    weak: ['crops', 'overlays', 'colour and contrast edits'],
    refs: [
      { label: 'Teague, JOSA 1980', url: 'https://doi.org/10.1364/JOSA.70.000920' },
      { label: 'Khotanzad & Hong, IEEE TPAMI 1990', url: 'https://doi.org/10.1109/34.55109' },
    ],
  },
  {
    id: 'huMoments',
    group: 'texture',
    name: 'Hu moment shape match',
    by: 'Hu 1962 · OpenCV matchShapes (method I2)',
    metric: 'difference of 7 moment invariants',
    better: 'lower',
    match: 0.00113,
    partial: 0.0109,
    format: (v) => (v < 0.001 ? v.toExponential(1) : v.toPrecision(2)),
    about: 'Compares seven “moment invariants” of each picture’s brightness — statistics unchanged by moving, scaling, rotating or mirroring it. The oldest invariant shape descriptor (1962), still built into OpenCV.',
    thresholds: '≤ 0.0011: match. 0.0011–0.011: partial. (1% and 5% of unrelated test pairs pass.)',
    robust: ['rotation', 'mirroring', 'resizing'],
    weak: ['crops', 'overlays', 'contrast edits', 'unrelated images with a similar balance of light'],
    refs: [
      { label: 'Hu, IRE Trans. Inf. Theory 1962', url: 'https://doi.org/10.1109/TIT.1962.1057692' },
      { label: 'OpenCV matchShapes', url: 'https://docs.opencv.org/4.x/d3/dc0/group__imgproc__shape.html' },
    ],
  },

  // ------------------------------------------------------------ metadata
  {
    id: 'exif',
    group: 'meta',
    name: 'EXIF capture metadata',
    by: 'camera, timestamp, unique ID',
    metric: 'matching capture fields',
    better: 'equal',
    about: 'Compares camera make/model/serial, capture time and image ID stored by cameras and phones. Matching capture data suggests both files came from the same original photo.',
    thresholds: 'Same unique ID, or same camera and same capture time: match. Same camera only: partial. Not applicable if either file has no EXIF (most web images are stripped).',
    robust: ['edits in many apps preserve EXIF'],
    weak: ['trivially removed or forged', 'screenshots and most web uploads strip it'],
    refs: [{ label: 'EXIF 2.32 spec', url: 'https://www.cipa.jp/std/documents/e/DC-X008-Translation-2019-E.pdf' }],
  },
  {
    id: 'sdmark',
    group: 'meta',
    name: 'Stable Diffusion watermark',
    by: 'invisible-watermark “dwtDct”, as in the SD reference code',
    metric: 'share of watermark bits recovered',
    better: 'equal',
    about:
      'The Stable Diffusion 1.x and 2.x reference scripts, and the SDXL pipeline in Hugging Face diffusers, hide a short message in every image they make (“StableDiffusionV1”, “SDV2”, or a 48-bit SDXL code), using the invisible-watermark library’s DWT-DCT method. This test reads the hidden bits back. Finding the mark shows the image left one of those pipelines unmodified.',
    thresholds: '≥ 90% of a known message’s bits recovered: found (unmarked images give about 50%). Absence proves nothing — most other generators do not add this mark, and any resize, crop or JPEG re-save erases it.',
    robust: ['lossless saving (PNG)'],
    weak: ['resizing, cropping, JPEG re-saving', 'tools that skip the watermark'],
    refs: [
      { label: 'invisible-watermark (ShieldMnt)', url: 'https://github.com/ShieldMnt/invisible-watermark' },
      { label: 'Stable Diffusion txt2img.py', url: 'https://github.com/CompVis/stable-diffusion/blob/main/scripts/txt2img.py' },
    ],
  },
  {
    id: 'c2pa',
    group: 'meta',
    name: 'Content Credentials (C2PA)',
    by: 'signed provenance manifests · official C2PA SDK',
    metric: 'what each file’s signed history says',
    better: 'equal',
    about:
      'C2PA “Content Credentials” are cryptographically signed records attached to a file: which tool made or edited it, what was done, whether generative AI was involved, and which earlier files (“ingredients”) went into it. Adobe, OpenAI, Google, Microsoft and several camera makers write them. This test reads each file’s credentials with the official C2PA SDK and checks whether B lists A as an ingredient.',
    thresholds: 'B lists A as an ingredient (or A lists B): match. Credentials present but unrelated: shown for information. No credentials in either file: not applicable — most images have none, and removing them is easy.',
    robust: ['edits in tools that support C2PA'],
    weak: ['stripped by most websites and by screenshots', 'only as trustworthy as the signer'],
    refs: [
      { label: 'C2PA specification', url: 'https://c2pa.org/specifications/' },
      { label: 'Content Authenticity Initiative', url: 'https://contentauthenticity.org/' },
    ],
  },
  {
    id: 'cmi',
    group: 'meta',
    name: 'Copyright notices (CMI)',
    by: 'creator, copyright, credit and licence fields',
    metric: 'whether B keeps A’s credit and rights fields',
    better: 'equal',
    about:
      'Reads the credit lines a file carries — XMP dc:creator and dc:rights, IPTC By-line, Copyright Notice and Credit, EXIF Artist and Copyright, licence links — and checks whether B still carries A’s. The law calls these “copyright management information”: removing or altering them knowingly can be its own violation (17 U.S.C. § 1202), as in the claims over watermarks in Getty Images v. Stability AI.',
    thresholds: 'Same credits: match. Some kept: partial. A’s credits missing from B: flagged as removed. Not applicable when neither file credits anyone.',
    robust: ['edits in apps that preserve metadata'],
    weak: ['metadata is often stripped by websites and messaging apps', 'easily forged'],
    refs: [
      { label: '17 U.S.C. § 1202', url: 'https://www.law.cornell.edu/uscode/text/17/1202' },
      { label: 'IPTC Photo Metadata Standard', url: 'https://iptc.org/standards/photo-metadata/iptc-standard/' },
    ],
  },
  {
    id: 'lineage',
    group: 'meta',
    name: 'Edit history (XMP lineage)',
    by: 'DocumentID, DerivedFrom, DocumentAncestors, History',
    metric: 'does either file say it was made from the other?',
    better: 'equal',
    about:
      'Editing software (Photoshop, Lightroom, GIMP, many phone apps) stamps files with document IDs and records what each was derived from and which files were placed into it. If B’s history names A’s ID, B says of itself that it was made from A. Also reports generator settings that AI image tools write into PNG files (prompt, seed, model).',
    thresholds: 'B names A (or A names B), or both share an original document ID: match. IDs present but unrelated: no link.',
    robust: ['edits in Adobe and many other apps'],
    weak: ['stripped by most websites', 'can be edited by hand'],
    refs: [{ label: 'XMP Media Management schema', url: 'https://developer.adobe.com/xmp/docs/XMPNamespaces/xmpMM/' }],
  },
  {
    id: 'jpegq',
    group: 'meta',
    name: 'JPEG encoder fingerprint',
    by: 'quantization tables, quality, chroma subsampling',
    metric: 'identical encoder settings',
    better: 'equal',
    about:
      'Every JPEG stores the quantization tables its encoder used; together with chroma subsampling and the progressive/baseline mode they form a fingerprint of the software and quality setting that last saved the file (Kee, Johnson & Farid 2011). Identical tables mean the same kind of encoder at the same setting; a lower quality in B fits B being a re-save of A.',
    thresholds: 'Identical tables and subsampling: match. Otherwise the estimated qualities are shown.',
    robust: ['metadata removal'],
    weak: ['many programs share the standard libjpeg tables', 'says nothing about content'],
    refs: [{ label: 'Kee, Johnson & Farid, IEEE TIFS 2011', url: 'https://doi.org/10.1109/TIFS.2011.2128309' }],
  },
  {
    id: 'thumbnail',
    group: 'meta',
    name: 'Embedded preview check',
    by: 'EXIF thumbnail vs both images (dHash)',
    metric: 'what the embedded preview shows',
    better: 'equal',
    about:
      'Cameras and editors embed a small preview in the EXIF data. Some editors change the picture without updating the preview, so a cropped or retouched file can still carry a preview of the original. This test compares each preview with its own image and with the other image.',
    thresholds: 'A preview that shows the other image rather than its own: match. A preview that matches neither: stale (edited after the preview was written).',
    robust: ['crops and retouching that leave EXIF alone'],
    weak: ['most web images have no preview', 'previews are easy to remove'],
    refs: [{ label: 'Kee & Farid, Digital image authentication from thumbnails (SPIE 2010)', url: 'https://doi.org/10.1117/12.838834' }],
  },
  {
    id: 'icc',
    group: 'meta',
    name: 'Colour profile (ICC)',
    by: 'embedded ICC profile · ICC.1 header and description',
    metric: 'same embedded colour profile?',
    better: 'equal',
    about:
      'Cameras, scanners and editing programs embed an ICC colour profile saying how to interpret the file’s numbers as colours. Standard profiles (sRGB, Display P3, Adobe RGB) are shared by millions of files, but a custom profile — a particular camera, scanner or printer calibration — is a fingerprint of where a file has been.',
    thresholds: 'Byte-identical custom profile: match. Identical standard profile, or same profile name: partial. Different profiles: no match. Not applicable unless both files embed one.',
    robust: ['editing in colour-managed software', 'metadata-preserving re-saves'],
    weak: ['stripped by many websites', 'standard profiles prove little'],
    refs: [{ label: 'ICC.1:2022 specification', url: 'https://www.color.org/specification/ICC.1-2022-05.pdf' }],
  },
  {
    id: 'dims',
    group: 'meta',
    name: 'Dimensions & aspect ratio',
    by: 'pixel width and height',
    metric: 'same size, or the same shape at another size?',
    better: 'equal',
    about: 'The plainest clue: a re-save keeps the exact pixel dimensions, a resize keeps the shape (aspect ratio), and a crop changes both. Weak evidence on its own, since cameras, phones and image generators all produce standard sizes.',
    thresholds: 'Same width and height: partial (shared by many unrelated images). Same shape at another size, or turned 90°: shown for information. Anything else: no match.',
    robust: ['re-saving', 'metadata edits'],
    weak: ['any resize or crop', 'unrelated images of standard sizes'],
    refs: [],
  },
  {
    id: 'gps',
    group: 'meta',
    name: 'GPS location',
    by: 'EXIF GPS latitude and longitude',
    metric: 'distance between the recorded locations',
    better: 'lower',
    match: 100,
    partial: 5000,
    format: (v) => (v < 1000 ? `${Math.round(v)} m apart` : `${(v / 1000).toFixed(1)} km apart`),
    about: 'Phones stamp photos with where they were taken. Two files tagged within a few metres of each other were probably shot at the same spot — though not necessarily by the same person, and the tags are easy to edit or remove.',
    thresholds: '≤ 100 m: match. ≤ 5 km: partial. Not applicable unless both files carry GPS tags (most websites strip them).',
    robust: ['edits that preserve EXIF'],
    weak: ['stripped by most websites and messaging apps', 'easily edited'],
    refs: [{ label: 'EXIF 2.32 spec (GPS IFD)', url: 'https://www.cipa.jp/std/documents/e/DC-X008-Translation-2019-E.pdf' }],
  },
];

export const ENGINE_BY_ID = Object.fromEntries(ENGINES.map((e) => [e.id, e]));

/** Map a numeric score to a verdict using the engine's thresholds. */
export function verdictFor(engine, value) {
  if (value === null || value === undefined || Number.isNaN(value)) return 'na';
  if (engine.better === 'higher') {
    if (value >= engine.match) return 'match';
    if (engine.partial !== null && engine.partial !== undefined && value >= engine.partial) return 'partial';
    return 'none';
  }
  if (engine.better === 'lower') {
    if (value <= engine.match) return 'match';
    if (engine.partial !== null && engine.partial !== undefined && value <= engine.partial) return 'partial';
    return 'none';
  }
  return value ? 'identical' : 'none';
}

export const VERDICT_LABEL = {
  identical: 'Identical',
  match: 'Match',
  partial: 'Partial',
  none: 'No match',
  na: 'N/A',
  info: 'Found',
  error: 'Error',
  skipped: 'Off',
  pending: 'Waiting',
  running: 'Running',
};
