// The catalogue of tests ("engines"): what each one measures, how its score
// is read, the thresholds used for the verdict, and short teaching notes.
// Shared by the UI and the analysis worker.

export const GROUPS = [
  {
    id: 'neural',
    title: 'Neural copy detection',
    blurb:
      'Deep networks map each image to a vector ("embedding"); similar images land close together. SSCD is trained specifically to recognise copies, while CLIP and DINOv2 measure general visual or semantic resemblance.',
  },
  {
    id: 'objects',
    title: 'Objects',
    blurb:
      'An object detector (D-FINE, trained on the 365 everyday categories of Objects365) finds things like hats, pictures and tables in each image. The objects are paired up across the two images and compared one by one; the Objects tab shows the marked-up images.',
  },
  {
    id: 'exact',
    title: 'Exact & verbatim copies',
    blurb:
      'Bit-level checks. They only fire on literal copies: change a single byte or pixel and they report "different".',
  },
  {
    id: 'hash',
    title: 'Perceptual hashes',
    blurb:
      'Each image is reduced to a short fingerprint that survives resizing and re-compression. Fingerprints are compared by counting differing bits (Hamming distance). These are the workhorses of large-scale duplicate and abuse-material detection.',
  },
  {
    id: 'geometry',
    title: 'Keypoints & geometry',
    blurb:
      'Classic computer vision: find distinctive corners/blobs in both images, match them, and check whether one consistent geometric transform (a homography) explains the matches. Robust to cropping, scaling and rotation.',
  },
  {
    id: 'structure',
    title: 'Pixel & structural similarity',
    blurb:
      'Full-reference image-quality metrics. Image B is resized to image A’s dimensions and compared location by location, so they assume the two images are aligned.',
  },
  {
    id: 'color',
    title: 'Color & histograms',
    blurb:
      'Compare the overall distribution of colours or brightness, ignoring where they occur. Fast and invariant to geometry, but two unrelated images with similar palettes look alike.',
  },
  {
    id: 'meta',
    title: 'Metadata',
    blurb: 'Information stored alongside the pixels (camera, timestamp). Easy to strip or forge.',
  },
];

const pct = (v) => `${(v * 100).toFixed(v >= 0.995 && v < 1 ? 1 : 0)}%`;
const f3 = (v) => v.toFixed(3);
const f2 = (v) => v.toFixed(2);
const bits = (n) => (d) => `${d} / ${n} bits`;

const HASH64 = { better: 'lower', match: 8, partial: 14, format: bits(64) };

export const ENGINES = [
  // ------------------------------------------------------------ neural
  {
    id: 'sscd',
    group: 'neural',
    name: 'SSCD copy detector',
    by: 'Meta AI · ResNet-50 · sscd_disc_mixup',
    featured: true,
    metric: 'cosine similarity of 512-d descriptors',
    better: 'higher',
    match: 0.75,
    partial: 0.5,
    format: f3,
    model: 'sscd',
    about:
      'A Self-Supervised Descriptor for image Copy Detection, trained to give near-identical vectors to an image and its edited copies (crops, overlays, colour changes, compression) while separating merely similar-looking photos.',
    thresholds:
      '≥ 0.75: copy (the SSCD authors report 90% precision at this point on the DISC2021 benchmark). 0.50–0.75: possible partial copy — Somepalli et al. treat scores above 0.5 as likely "partial object-level copies". Below 0.5: not a copy.',
    robust: ['resizing', 'compression', 'colour edits', 'overlays & text', 'flips', 'moderate crops'],
    weak: ['heavy crops of a small region', 'large rotations', 'redrawn or restyled copies'],
    refs: [
      { label: 'Pizzi et al., CVPR 2022', url: 'https://arxiv.org/abs/2202.10261' },
      { label: 'Code & models (MIT)', url: 'https://github.com/facebookresearch/sscd-copy-detection' },
    ],
    pipeline: 'Short edge resized to 288 px (bilinear), ImageNet normalisation — the preprocessing recommended in the SSCD README.',
  },
  {
    id: 'sscdAligned',
    group: 'neural',
    name: 'SSCD after alignment',
    by: 'SSCD on the shared region, with crop / rotation / perspective undone',
    metric: 'cosine similarity of SSCD descriptors of the aligned overlap',
    better: 'higher',
    match: 0.75,
    partial: 0.5,
    format: f3,
    model: 'sscd',
    about:
      'A copy detector looks at whole images, so a copy that was rotated, put in perspective, cut down to a corner or pasted into a larger picture can score low. This test first lines B up with A using the keypoint transform, then runs SSCD on just the region the two images share — the same comparison a person makes after holding the two side by side and turning one to match.',
    thresholds: 'Same scale as SSCD: ≥ 0.75 copy, 0.50–0.75 possible partial copy. Only runs when keypoint matching finds a consistent transform.',
    robust: ['rotation', 'perspective', 'heavy crops', 'copies pasted into a larger image'],
    weak: ['redrawn or restaged copies (no keypoint transform)', 'mirror images'],
    refs: [{ label: 'Pizzi et al., CVPR 2022 (SSCD)', url: 'https://arxiv.org/abs/2202.10261' }],
    pipeline: 'Keypoint homography (best of ORB, AKAZE, BRISK) → warp B into A’s frame (≤ 640 px) → crop both to the overlap, grey outside it → SSCD (short edge 288).',
  },
  {
    id: 'sscdLarge',
    group: 'neural',
    name: 'SSCD · replication-study setting',
    by: 'Meta AI · ResNeXt-101 · sscd_disc_large',
    featured: true,
    metric: 'cosine similarity of 1024-d descriptors',
    better: 'higher',
    match: 0.5,
    partial: null,
    format: f3,
    model: 'sscdLarge',
    about:
      'Reproduces how Somepalli et al. measured whether diffusion models replicate their training images, following the configuration in the authors’ published code: the large SSCD model with resize-256 / centre-crop-224 preprocessing. Only the centre crop is compared, so borders are ignored.',
    thresholds:
      '> 0.50: replication. Somepalli et al. found generations above 0.5 "exhibit strong visual similarities" and are "likely to be partial object-level copies" of training data; in the NeurIPS 2023 paper they used > 0.7 to find nearly identical duplicates in LAION.',
    robust: ['resizing', 'compression', 'colour edits', 'flips'],
    weak: ['content outside the centre crop', 'heavy crops', 'large rotations'],
    refs: [
      { label: 'Somepalli et al., NeurIPS 2023', url: 'https://arxiv.org/abs/2305.20086' },
      { label: 'Somepalli et al., CVPR 2023', url: 'https://arxiv.org/abs/2212.03860' },
      { label: 'DCR code', url: 'https://github.com/somepago/DCR' },
    ],
    pipeline: 'Resize short edge to 256 (bilinear), centre crop 224×224, normalise to [-1, 1] — exactly as in the DCR repository.',
  },
  {
    id: 'dino',
    group: 'neural',
    name: 'DINOv2 embedding',
    by: 'Meta AI · ViT-S/14',
    metric: 'cosine similarity of the CLS token',
    better: 'higher',
    match: 0.85,
    partial: 0.4,
    format: f3,
    model: 'dino',
    about:
      'A self-supervised vision transformer whose features capture object identity and layout. Widely used for image retrieval; it responds to "same object/scene" more than to "same pixels".',
    thresholds: '≥ 0.85: near-duplicate content. 0.40–0.85: same subject, pose or scene (a staged recreation of a photo scores about 0.5). Below 0.40: different content; unrelated photos score near 0. (Heuristic thresholds.)',
    robust: ['resizing', 'compression', 'colour edits', 'moderate crops', 'small rotations'],
    weak: ['flags different photos of the same object', 'large crops'],
    refs: [{ label: 'Oquab et al., 2023', url: 'https://arxiv.org/abs/2304.07193' }],
    pipeline: 'Resize short edge to 256 (bicubic), centre crop 224, ImageNet normalisation (Hugging Face preprocessing).',
  },
  {
    id: 'clip',
    group: 'neural',
    name: 'CLIP embedding',
    by: 'OpenAI · ViT-B/32',
    metric: 'cosine similarity of image embeddings',
    better: 'higher',
    match: 0.95,
    partial: 0.75,
    format: f3,
    model: 'clip',
    about:
      'CLIP was trained to match images with captions, so its embedding encodes what an image is about. Two different photos of a red sports car score high; it measures semantic similarity, not copying.',
    thresholds: '≥ 0.95: near-duplicate. 0.75–0.95: semantically similar (same kind of content). Below 0.75: different. Unrelated photos still typically score 0.4–0.6. (Heuristic thresholds.)',
    robust: ['almost every edit', 'style changes'],
    weak: ['cannot tell a copy from a new image of the same subject'],
    refs: [{ label: 'Radford et al., ICML 2021', url: 'https://arxiv.org/abs/2103.00020' }],
    pipeline: 'Resize short edge to 224 (bicubic), centre crop 224, CLIP normalisation (Hugging Face preprocessing).',
  },
  {
    id: 'lpips',
    group: 'neural',
    name: 'LPIPS perceptual distance',
    by: 'Zhang et al. · AlexNet v0.1',
    metric: 'learned perceptual distance (0 = identical)',
    better: 'lower',
    match: 0.2,
    partial: 0.4,
    format: f3,
    model: 'lpips',
    about:
      'Compares deep network activations location by location, calibrated against human judgements of how different two images look. Like SSIM it assumes aligned images, so geometric edits push it up.',
    thresholds: '≤ 0.20: perceptually close. 0.20–0.40: noticeably different. Above 0.40: different (unrelated images ≈ 0.6–0.8).',
    robust: ['compression', 'mild blur/noise'],
    weak: ['crops, flips, rotations (misalignment)'],
    refs: [{ label: 'Zhang et al., CVPR 2018', url: 'https://arxiv.org/abs/1801.03924' }],
    pipeline: 'Both images resized to A’s aspect ratio with a 256 px long side, scaled to [-1, 1].',
  },

  // ------------------------------------------------------------ objects
  {
    id: 'objects',
    group: 'objects',
    name: 'Object-level comparison',
    by: 'D-FINE-M detector · Objects365 · 365 categories',
    metric: 'objects paired across the two images, and how many changed',
    better: 'equal',
    model: 'dfine',
    about:
      'Detects objects in both images and pairs them up — by position when the images can be aligned with keypoints, otherwise by kind and appearance — then compares each pair: the pixels inside the object (when aligned) and the SSCD copy similarity of the two cut-outs.',
    thresholds:
      'Match: at least 80% of the objects appear in both images unchanged. Partial: at least half of them pair up. An aligned object counts as changed when more than 10% of its pixels change colour (ΔE₀₀ > 6) or its SSIM falls below 0.8.',
    robust: ['crops', 'rescaling', 'objects that move (matched by appearance)'],
    weak: ['things outside the 365 categories', 'small or hidden objects', 'stylised or abstract art'],
    refs: [
      { label: 'D-FINE (Peng et al., ICLR 2025)', url: 'https://arxiv.org/abs/2410.13842' },
      { label: 'Objects365 (Shao et al., ICCV 2019)', url: 'https://doi.org/10.1109/ICCV.2019.00852' },
    ],
    pipeline: 'Each image resized to 640×640; detections above 0.35 confidence; duplicates suppressed so each object keeps one label.',
  },

  // ------------------------------------------------------------ exact
  {
    id: 'sha256',
    group: 'exact',
    name: 'SHA-256 file hash',
    by: 'cryptographic digest of the file bytes',
    metric: 'exact equality',
    better: 'equal',
    about:
      'A cryptographic fingerprint of the file. Identical digests mean the files are byte-for-byte the same; any change (even metadata or re-saving at the same quality) produces a completely different digest.',
    thresholds: 'Identical digest ⇒ identical file. Otherwise the test says nothing about visual similarity.',
    robust: ['nothing — by design'],
    weak: ['any change at all, including invisible ones'],
    refs: [{ label: 'FIPS 180-4', url: 'https://csrc.nist.gov/pubs/fips/180-4/upd1/final' }],
  },
  {
    id: 'sha1',
    group: 'exact',
    name: 'SHA-1 file hash',
    by: 'legacy cryptographic digest',
    metric: 'exact equality',
    better: 'equal',
    about: 'Older 160-bit digest, still common in forensic tools. Deliberate collisions are practical (2017), so it should not be trusted against an adversary.',
    thresholds: 'Identical digest ⇒ identical file (barring a deliberate collision).',
    robust: ['nothing — by design'],
    weak: ['any change at all'],
    refs: [{ label: 'SHAttered (2017)', url: 'https://shattered.io/' }],
  },
  {
    id: 'md5',
    group: 'exact',
    name: 'MD5 file hash',
    by: 'legacy cryptographic digest',
    metric: 'exact equality',
    better: 'equal',
    about: 'The 128-bit digest used by many older hash databases. Collisions can be manufactured in seconds, so it only proves identity for non-adversarial data.',
    thresholds: 'Identical digest ⇒ identical file (barring a deliberate collision).',
    robust: ['nothing — by design'],
    weak: ['any change at all'],
    refs: [{ label: 'RFC 1321', url: 'https://www.rfc-editor.org/rfc/rfc1321' }],
  },
  {
    id: 'payload',
    group: 'exact',
    name: 'Same image data (metadata ignored)',
    by: 'SHA-256 of the compressed image data alone',
    metric: 'exact equality of the encoded image',
    better: 'equal',
    about:
      'Splits each file into its compressed picture (JPEG scans and tables, PNG image chunks, WebP bitstream) and its metadata (EXIF, XMP, IPTC, ICC, comments), and hashes only the picture. Equal hashes with different files mean somebody changed or stripped the metadata without re-saving the image.',
    thresholds: 'Identical: same encoded picture, so B was not re-compressed — only its metadata differs.',
    robust: ['metadata edits and removal'],
    weak: ['any re-save, even at the same quality', 'different file formats'],
    refs: [{ label: 'JPEG (ITU-T T.81)', url: 'https://www.w3.org/Graphics/JPEG/itu-t81.pdf' }],
  },
  {
    id: 'pixels',
    group: 'exact',
    name: 'Pixel-exact match',
    by: 'decoded RGBA values',
    metric: 'share of identical pixels',
    better: 'equal',
    about:
      'Decodes both files and compares every pixel. Catches identical images saved in different formats or with different metadata (e.g. PNG vs. lossless WebP), which file hashes miss.',
    thresholds: 'All pixels equal (and same dimensions) ⇒ identical image. Any lossy re-encoding breaks it.',
    robust: ['metadata changes', 'lossless format conversion'],
    weak: ['JPEG re-compression', 'any edit or resize'],
    refs: [],
  },
  {
    id: 'crop',
    group: 'exact',
    name: 'Verbatim crop search',
    by: 'template matching · OpenCV',
    metric: 'normalised cross-correlation of the best placement',
    better: 'higher',
    match: 0.97,
    partial: 0.9,
    format: f3,
    about:
      'Checks whether the smaller image appears inside the larger one at the same scale — a cut-out or screenshot of part of the image. When the best placement matches pixel-for-pixel it reports a verbatim (lossless) crop.',
    thresholds: '≥ 0.97: the smaller image is a crop of the larger one. 0.90–0.97: probable crop with edits/compression. Only runs when one image is smaller in both dimensions.',
    robust: ['compression', 'small brightness changes'],
    weak: ['rescaling', 'rotation', 'same-size images (not applicable)'],
    refs: [{ label: 'OpenCV matchTemplate', url: 'https://docs.opencv.org/4.x/df/dfb/group__imgproc__object.html' }],
  },

  // ------------------------------------------------------------ hashes
  {
    id: 'pdq',
    group: 'hash',
    name: 'PDQ',
    by: 'Meta · 256-bit DCT hash',
    metric: 'Hamming distance',
    better: 'lower',
    match: 31,
    partial: 63,
    format: bits(256),
    about:
      'The perceptual hash Meta open-sourced for sharing hashes of harmful content between platforms (alongside Microsoft’s proprietary PhotoDNA). It keeps the signs of 256 low-frequency DCT coefficients of a blurred 64×64 luminance image.',
    thresholds: '≤ 31 bits: match — Meta’s recommended threshold. 32–63: weak similarity. Unrelated images average ~128.',
    robust: ['resizing', 'compression', 'mild colour edits', 'small overlays'],
    weak: ['crops', 'rotations', 'mirroring (see next row)'],
    refs: [
      { label: 'PDQ white paper', url: 'https://github.com/facebook/ThreatExchange/blob/main/hashing/hashing.pdf' },
      { label: 'Reference code', url: 'https://github.com/facebook/ThreatExchange/tree/main/pdq' },
    ],
  },
  {
    id: 'pdqDihedral',
    group: 'hash',
    name: 'PDQ + rotations/mirrors',
    by: 'Meta · 8 dihedral variants',
    metric: 'smallest Hamming distance over 8 orientations',
    better: 'lower',
    match: 31,
    partial: 63,
    format: bits(256),
    about:
      'PDQ can cheaply derive the hashes of an image rotated by 90°/180°/270° or mirrored. Comparing against all eight orientations defeats the simplest evasion trick: flipping the image.',
    thresholds: 'Same as PDQ (≤ 31 bits: match).',
    robust: ['90° rotations', 'mirroring', 'plus everything PDQ tolerates'],
    weak: ['crops', 'arbitrary-angle rotation'],
    refs: [{ label: 'Reference code', url: 'https://github.com/facebook/ThreatExchange/tree/main/pdq' }],
  },
  {
    id: 'phash',
    group: 'hash',
    name: 'pHash',
    by: 'DCT perceptual hash · imagehash',
    metric: 'Hamming distance',
    ...HASH64,
    about: 'Shrinks the image to 32×32 grey, takes the discrete cosine transform and records whether each of the 64 lowest frequencies is above the median.',
    thresholds: '≤ 8 bits: match. 9–14: possible. Unrelated images average ~32.',
    robust: ['resizing', 'compression', 'brightness/contrast'],
    weak: ['crops', 'rotations', 'mirroring'],
    refs: [{ label: 'Krawetz, “Looks Like It”', url: 'https://www.hackerfactor.com/blog/index.php?/archives/432-Looks-Like-It.html' }],
  },
  {
    id: 'dhash',
    group: 'hash',
    name: 'dHash',
    by: 'difference hash · imagehash',
    metric: 'Hamming distance',
    ...HASH64,
    about: 'Shrinks to 9×8 grey and records whether each pixel is brighter than its right-hand neighbour, i.e. the direction of horizontal gradients.',
    thresholds: '≤ 8 bits: match. 9–14: possible.',
    robust: ['resizing', 'compression', 'brightness/contrast'],
    weak: ['crops', 'rotations', 'mirroring'],
    refs: [{ label: 'Krawetz, “Kind of Like That”', url: 'https://www.hackerfactor.com/blog/index.php?/archives/529-Kind-of-Like-That.html' }],
  },
  {
    id: 'ahash',
    group: 'hash',
    name: 'aHash',
    by: 'average hash · imagehash',
    metric: 'Hamming distance',
    ...HASH64,
    about: 'The simplest perceptual hash: shrink to 8×8 grey and record which pixels are brighter than the mean.',
    thresholds: '≤ 8 bits: match. 9–14: possible.',
    robust: ['resizing', 'compression'],
    weak: ['crops', 'rotations', 'large dark/bright overlays', 'gamma changes'],
    refs: [{ label: 'imagehash', url: 'https://github.com/JohannesBuchner/imagehash' }],
  },
  {
    id: 'whash',
    group: 'hash',
    name: 'wHash',
    by: 'Haar wavelet hash · imagehash',
    metric: 'Hamming distance',
    ...HASH64,
    about: 'Uses a Haar wavelet decomposition instead of a DCT: compares the 8×8 low-frequency wavelet coefficients (after removing the overall brightness) with their median.',
    thresholds: '≤ 8 bits: match. 9–14: possible.',
    robust: ['resizing', 'compression', 'brightness'],
    weak: ['crops', 'rotations', 'mirroring'],
    refs: [{ label: 'imagehash', url: 'https://github.com/JohannesBuchner/imagehash' }],
  },
  {
    id: 'blockhash',
    group: 'hash',
    name: 'Blockhash',
    by: 'block mean value hash · blockhash.io',
    metric: 'Hamming distance',
    better: 'lower',
    match: 24,
    partial: 48,
    format: bits(256),
    about: 'Splits the image into a 16×16 grid and records, band by band, whether each block is brighter than the band median (Yang, Gu & Niu 2006). Popularised by the Commons Machinery project for matching images to Wikimedia Commons.',
    thresholds: '≤ 24 bits: match. 25–48: possible. Unrelated images average ~128.',
    robust: ['resizing', 'compression', 'colour edits'],
    weak: ['crops', 'rotations', 'mirroring'],
    refs: [{ label: 'blockhash.io', url: 'https://github.com/commonsmachinery/blockhash-js' }],
  },

  // ------------------------------------------------------------ geometry
  {
    id: 'orb',
    group: 'geometry',
    name: 'ORB keypoints + RANSAC',
    by: 'OpenCV · Rublee et al. 2011',
    metric: 'geometrically consistent matches (inliers)',
    better: 'higher',
    match: 20,
    partial: 10,
    format: (v) => `${v} inliers`,
    about: 'Finds up to 3,000 corner features per image, matches their binary descriptors (Lowe ratio test), then uses RANSAC to find the largest set of matches explained by a single homography.',
    thresholds: '≥ 20 inliers (and ≥ 50% of matches) with a plausible transform: shared content. 10–19: partial. Unrelated pairs usually give < 10.',
    robust: ['crops', 'rotation', 'scaling', 'compression', 'colour edits', 'overlays'],
    weak: ['mirroring', 'heavy blur', 'flat or repetitive images'],
    refs: [{ label: 'Rublee et al., ICCV 2011', url: 'https://doi.org/10.1109/ICCV.2011.6126544' }],
  },
  {
    id: 'akaze',
    group: 'geometry',
    name: 'AKAZE keypoints + RANSAC',
    by: 'OpenCV · Alcantarilla et al. 2013',
    metric: 'geometrically consistent matches (inliers)',
    better: 'higher',
    match: 20,
    partial: 10,
    format: (v) => `${v} inliers`,
    about: 'Detects blob-like features in a nonlinear scale space, which preserves object edges; scale- and rotation-invariant with binary descriptors.',
    thresholds: 'Same as ORB.',
    robust: ['crops', 'rotation', 'scaling', 'compression', 'blur'],
    weak: ['mirroring', 'flat images'],
    refs: [{ label: 'Alcantarilla et al., BMVC 2013', url: 'https://doi.org/10.5244/C.27.13' }],
  },
  {
    id: 'brisk',
    group: 'geometry',
    name: 'BRISK keypoints + RANSAC',
    by: 'OpenCV · Leutenegger et al. 2011',
    metric: 'geometrically consistent matches (inliers)',
    better: 'higher',
    match: 20,
    partial: 10,
    format: (v) => `${v} inliers`,
    about: 'Scale-space corner detector with a binary descriptor built from brightness comparisons on a circular sampling pattern.',
    thresholds: 'Same as ORB.',
    robust: ['crops', 'rotation', 'scaling', 'compression'],
    weak: ['mirroring', 'blur', 'flat images'],
    refs: [{ label: 'Leutenegger et al., ICCV 2011', url: 'https://doi.org/10.1109/ICCV.2011.6126542' }],
  },
  {
    id: 'alignedSsim',
    group: 'geometry',
    name: 'SSIM after alignment',
    by: 'homography warp + SSIM',
    metric: 'SSIM over the overlapping region',
    better: 'higher',
    match: 0.8,
    partial: 0.5,
    format: f3,
    about:
      'Uses the best keypoint transform to warp B onto A, then measures SSIM only where they overlap. Shows how much of the disagreement in plain SSIM was just misalignment (crop, rotation, scale).',
    thresholds: 'Same as SSIM. Not applicable when no consistent transform was found.',
    robust: ['crops', 'rotation', 'scaling'],
    weak: ['needs a keypoint match first'],
    refs: [],
  },

  // ------------------------------------------------------------ structure
  {
    id: 'ssim',
    group: 'structure',
    name: 'SSIM',
    by: 'Wang et al. 2004 · structural similarity',
    metric: 'mean SSIM (1 = identical)',
    better: 'higher',
    match: 0.8,
    partial: 0.5,
    format: f3,
    about:
      'Compares local luminance, contrast and structure in 11×11 Gaussian windows and averages the result. The most widely used full-reference image quality metric.',
    thresholds: '≥ 0.80: same image with mild distortion. 0.50–0.80: noticeably altered. Below 0.50: different or misaligned (unrelated photos ≈ 0.1–0.3).',
    robust: ['compression', 'uniform brightness shifts', 'colour changes (luma only)'],
    weak: ['any misalignment: crops, rotations, flips'],
    refs: [{ label: 'Wang et al., IEEE TIP 2004', url: 'https://doi.org/10.1109/TIP.2003.819861' }],
  },
  {
    id: 'msssim',
    group: 'structure',
    name: 'MS-SSIM',
    by: 'Wang, Simoncelli & Bovik 2003',
    metric: 'multi-scale SSIM (1 = identical)',
    better: 'higher',
    match: 0.85,
    partial: 0.6,
    format: f3,
    about: 'SSIM evaluated at five successively halved resolutions and combined, so coarse structure counts as well as fine detail. Less sensitive to noise and blur than SSIM.',
    thresholds: '≥ 0.85: same image. 0.60–0.85: altered. Below 0.60: different or misaligned.',
    robust: ['compression', 'noise', 'blur'],
    weak: ['misalignment'],
    refs: [{ label: 'Wang et al., Asilomar 2003', url: 'https://doi.org/10.1109/ACSSC.2003.1292216' }],
  },
  {
    id: 'psnr',
    group: 'structure',
    name: 'PSNR',
    by: 'peak signal-to-noise ratio',
    metric: 'decibels (∞ = identical)',
    better: 'higher',
    match: 28,
    partial: 20,
    format: (v) => (v === Infinity ? '∞ dB' : `${v.toFixed(1)} dB`),
    about: 'Mean squared error between pixel values expressed on a log scale. Simple and standard for compression, but it treats every pixel difference the same, regardless of how visible it is.',
    thresholds: '≥ 28 dB: near-identical (typical of JPEG compression). 20–28 dB: visibly altered. Below 20 dB: different, or a global brightness/colour change.',
    robust: ['mild compression'],
    weak: ['brightness or colour shifts', 'misalignment'],
    refs: [],
  },
  {
    id: 'ncc',
    group: 'structure',
    name: 'Normalised cross-correlation',
    by: 'Pearson correlation of brightness',
    metric: 'correlation (1 = identical pattern)',
    better: 'higher',
    match: 0.9,
    partial: 0.7,
    format: f3,
    about: 'Correlates the brightness of corresponding pixels after removing each image’s mean and contrast, so uniform brightness/contrast changes do not matter.',
    thresholds: '≥ 0.90: match. 0.70–0.90: partial. Below 0.70: different or misaligned.',
    robust: ['brightness', 'contrast', 'compression'],
    weak: ['misalignment', 'local edits'],
    refs: [],
  },
  {
    id: 'uqi',
    group: 'structure',
    name: 'Universal Quality Index',
    by: 'Wang & Bovik 2002',
    metric: 'mean Q over 8×8 windows (1 = identical)',
    better: 'higher',
    match: 0.7,
    partial: 0.4,
    format: f3,
    about: 'The predecessor of SSIM: combines correlation, luminance distortion and contrast distortion in sliding 8×8 windows, without SSIM’s stabilising constants.',
    thresholds: '≥ 0.70: match. 0.40–0.70: partial. Below 0.40: different.',
    robust: ['compression', 'colour (grey only)'],
    weak: ['misalignment', 'noise'],
    refs: [{ label: 'Wang & Bovik, IEEE SPL 2002', url: 'https://doi.org/10.1109/97.995823' }],
  },
  {
    id: 'gmsd',
    group: 'structure',
    name: 'GMSD',
    by: 'Xue et al. 2014 · gradient similarity',
    metric: 'gradient magnitude similarity deviation (0 = identical)',
    better: 'lower',
    match: 0.1,
    partial: 0.18,
    format: f3,
    about: 'Compares edge strength (gradient magnitude) at every location; the spread of the per-pixel similarity map is the score. Sensitive to new or missing edges such as added text.',
    thresholds: '≤ 0.10: match. 0.10–0.18: partial. Above 0.18: different (unrelated ≈ 0.25–0.35).',
    robust: ['colour changes', 'brightness', 'compression'],
    weak: ['misalignment', 'blur', 'added text/edges'],
    refs: [{ label: 'Xue et al., IEEE TIP 2014', url: 'https://arxiv.org/abs/1308.3052' }],
  },
  {
    id: 'deltaE',
    group: 'structure',
    name: 'CIEDE2000 colour difference',
    by: 'CIE ΔE₀₀ · mean over pixels',
    metric: 'mean ΔE₀₀ (0 = identical colour)',
    better: 'lower',
    match: 5,
    partial: 12,
    format: (v) => `ΔE ${v.toFixed(1)}`,
    about: 'Converts both images to CIELAB and measures the perceptual colour difference at every pixel with the CIEDE2000 formula used in print and textile quality control. A ΔE of about 1–2 is the smallest difference people notice.',
    thresholds: '≤ 5: match. 5–12: partial. Above 12: different colours (or misaligned).',
    robust: ['compression', 'blur'],
    weak: ['colour/brightness edits', 'misalignment'],
    refs: [{ label: 'Sharma et al. 2005', url: 'https://doi.org/10.1002/col.20070' }],
  },
  {
    id: 'changed',
    group: 'structure',
    name: 'Changed-pixel ratio',
    by: 'share of pixels with ΔE₀₀ > 5',
    metric: 'fraction of visibly changed pixels',
    better: 'lower',
    match: 0.1,
    partial: 0.4,
    format: pct,
    about: 'The fraction of locations whose colour changed by more than ΔE₀₀ 5 — a plain-language answer to “how much of the picture was altered?”.',
    thresholds: '≤ 10% changed: match. 10–40%: partial. More than 40%: different.',
    robust: ['compression', 'small local edits'],
    weak: ['global colour edits', 'misalignment'],
    refs: [],
  },
  {
    id: 'carlini',
    group: 'structure',
    name: 'Tiled ℓ2 extraction test',
    by: 'Carlini et al. 2023 · max over 16 tiles',
    metric: 'largest per-tile RMS pixel difference (0–1)',
    better: 'lower',
    match: 0.15,
    partial: null,
    format: f3,
    about:
      'The test Carlini et al. used to decide that Stable Diffusion had regurgitated a training image: resize both images to 512×512, cut each into 16 tiles, and take the worst tile’s root-mean-square difference. Because it is the worst tile that counts, a near-copy with one changed corner fails, which keeps the test strict — it flags near-verbatim reproductions, not loose resemblance.',
    thresholds: '≤ 0.15: “extracted” — a near-verbatim reproduction in Carlini et al.’s sense. Above 0.15: not extracted (which says nothing about looser copying).',
    robust: ['compression', 'tiny colour shifts'],
    weak: ['any crop, shift, flip or rotation (needs pixel alignment)', 'a local edit in any one tile'],
    refs: [{ label: 'Carlini et al., Extracting Training Data from Diffusion Models (USENIX Security 2023)', url: 'https://arxiv.org/abs/2301.13188' }],
    pipeline: 'Both images resized to 512×512 (bilinear), 16 non-overlapping 128×128 tiles, RMS difference over RGB in [0, 1], maximum over tiles.',
  },

  // ------------------------------------------------------------ color
  {
    id: 'histCorrel',
    group: 'color',
    name: 'Hue–saturation histogram correlation',
    by: 'OpenCV HISTCMP_CORREL · 50×60 bins',
    metric: 'correlation (1 = same distribution)',
    better: 'higher',
    match: 0.9,
    partial: 0.7,
    format: f3,
    about: 'Builds a 2-D histogram of hue and saturation (ignoring brightness) and correlates the two histograms — the textbook OpenCV approach.',
    thresholds: '≥ 0.90: match. 0.70–0.90: partial. Below 0.70: different palettes.',
    robust: ['crops', 'rotation', 'mirroring', 'brightness'],
    weak: ['colour edits', 'unrelated images with similar palettes'],
    refs: [{ label: 'OpenCV tutorial', url: 'https://docs.opencv.org/4.x/d8/dc8/tutorial_histogram_comparison.html' }],
  },
  {
    id: 'histChi',
    group: 'color',
    name: 'χ² histogram distance',
    by: 'symmetric chi-square · hue–saturation',
    metric: 'distance (0 = identical, 1 = disjoint)',
    better: 'lower',
    match: 0.1,
    partial: 0.3,
    format: f3,
    about: 'Sums squared bin differences weighted by bin size, emphasising differences in rare colours.',
    thresholds: '≤ 0.10: match. 0.10–0.30: partial. Above 0.30: different.',
    robust: ['crops', 'rotation', 'mirroring'],
    weak: ['colour edits', 'similar palettes'],
    refs: [],
  },
  {
    id: 'histIntersect',
    group: 'color',
    name: 'Colour histogram intersection',
    by: 'Swain & Ballard 1991 · 8×8×8 RGB',
    metric: 'shared mass (1 = identical)',
    better: 'higher',
    match: 0.85,
    partial: 0.65,
    format: f3,
    about: 'The original "colour indexing" idea: the fraction of pixels whose RGB colour bin is shared by both images.',
    thresholds: '≥ 0.85: match. 0.65–0.85: partial. Below 0.65: different.',
    robust: ['crops', 'rotation', 'mirroring'],
    weak: ['colour/brightness edits', 'similar palettes'],
    refs: [{ label: 'Swain & Ballard, IJCV 1991', url: 'https://doi.org/10.1007/BF00130487' }],
  },
  {
    id: 'histBhatt',
    group: 'color',
    name: 'Bhattacharyya distance',
    by: 'OpenCV HISTCMP_BHATTACHARYYA',
    metric: 'distance (0 = identical, 1 = disjoint)',
    better: 'lower',
    match: 0.2,
    partial: 0.4,
    format: f3,
    about: 'Measures the overlap of two probability distributions (here hue–saturation histograms); common in object tracking.',
    thresholds: '≤ 0.20: match. 0.20–0.40: partial. Above 0.40: different.',
    robust: ['crops', 'rotation', 'mirroring'],
    weak: ['colour edits', 'similar palettes'],
    refs: [],
  },
  {
    id: 'lumaEmd',
    group: 'color',
    name: 'Brightness distribution (EMD)',
    by: 'Earth Mover’s distance · 256 bins',
    metric: 'normalised Wasserstein distance',
    better: 'lower',
    match: 0.02,
    partial: 0.05,
    format: f3,
    about: 'How much "work" it takes to reshape one brightness histogram into the other — small shifts in brightness cost little, unlike bin-by-bin measures.',
    thresholds: '≤ 0.02: match. 0.02–0.05: partial. Above 0.05: different.',
    robust: ['crops', 'rotation', 'mirroring', 'colour hue changes'],
    weak: ['brightness/contrast edits', 'unrelated images with similar tones'],
    refs: [{ label: 'Rubner et al., IJCV 2000', url: 'https://doi.org/10.1023/A:1026543900054' }],
  },

  // ------------------------------------------------------------ metadata
  {
    id: 'exif',
    group: 'meta',
    name: 'EXIF capture metadata',
    by: 'camera, timestamp, unique ID',
    metric: 'matching capture fields',
    better: 'equal',
    about: 'Compares camera make/model/serial, capture time and image ID stored by cameras and phones. Matching capture data suggests both files came from the same original photo.',
    thresholds: 'Same unique ID, or same camera and same capture time: match. Same camera only: partial. Not applicable if either file has no EXIF (most web images are stripped).',
    robust: ['edits in many apps preserve EXIF'],
    weak: ['trivially removed or forged', 'screenshots and most web uploads strip it'],
    refs: [{ label: 'EXIF 2.32 spec', url: 'https://www.cipa.jp/std/documents/e/DC-X008-Translation-2019-E.pdf' }],
  },
  {
    id: 'cmi',
    group: 'meta',
    name: 'Copyright notices (CMI)',
    by: 'creator, copyright, credit and licence fields',
    metric: 'whether B keeps A’s credit and rights fields',
    better: 'equal',
    about:
      'Reads the credit lines a file carries — XMP dc:creator and dc:rights, IPTC By-line, Copyright Notice and Credit, EXIF Artist and Copyright, licence links — and checks whether B still carries A’s. The law calls these “copyright management information”: removing or altering them knowingly can be its own violation (17 U.S.C. § 1202), as in the claims over watermarks in Getty Images v. Stability AI.',
    thresholds: 'Same credits: match. Some kept: partial. A’s credits missing from B: flagged as removed. Not applicable when neither file credits anyone.',
    robust: ['edits in apps that preserve metadata'],
    weak: ['metadata is often stripped by websites and messaging apps', 'easily forged'],
    refs: [
      { label: '17 U.S.C. § 1202', url: 'https://www.law.cornell.edu/uscode/text/17/1202' },
      { label: 'IPTC Photo Metadata Standard', url: 'https://iptc.org/standards/photo-metadata/iptc-standard/' },
    ],
  },
  {
    id: 'lineage',
    group: 'meta',
    name: 'Edit history (XMP lineage)',
    by: 'DocumentID, DerivedFrom, DocumentAncestors, History',
    metric: 'does either file say it was made from the other?',
    better: 'equal',
    about:
      'Editing software (Photoshop, Lightroom, GIMP, many phone apps) stamps files with document IDs and records what each was derived from and which files were placed into it. If B’s history names A’s ID, B says of itself that it was made from A. Also reports generator settings that AI image tools write into PNG files (prompt, seed, model).',
    thresholds: 'B names A (or A names B), or both share an original document ID: match. IDs present but unrelated: no link.',
    robust: ['edits in Adobe and many other apps'],
    weak: ['stripped by most websites', 'can be edited by hand'],
    refs: [{ label: 'XMP Media Management schema', url: 'https://developer.adobe.com/xmp/docs/XMPNamespaces/xmpMM/' }],
  },
  {
    id: 'jpegq',
    group: 'meta',
    name: 'JPEG encoder fingerprint',
    by: 'quantization tables, quality, chroma subsampling',
    metric: 'identical encoder settings',
    better: 'equal',
    about:
      'Every JPEG stores the quantization tables its encoder used; together with chroma subsampling and the progressive/baseline mode they form a fingerprint of the software and quality setting that last saved the file (Kee, Johnson & Farid 2011). Identical tables mean the same kind of encoder at the same setting; a lower quality in B fits B being a re-save of A.',
    thresholds: 'Identical tables and subsampling: match. Otherwise the estimated qualities are shown.',
    robust: ['metadata removal'],
    weak: ['many programs share the standard libjpeg tables', 'says nothing about content'],
    refs: [{ label: 'Kee, Johnson & Farid, IEEE TIFS 2011', url: 'https://doi.org/10.1109/TIFS.2011.2128309' }],
  },
  {
    id: 'thumbnail',
    group: 'meta',
    name: 'Embedded preview check',
    by: 'EXIF thumbnail vs both images (dHash)',
    metric: 'what the embedded preview shows',
    better: 'equal',
    about:
      'Cameras and editors embed a small preview in the EXIF data. Some editors change the picture without updating the preview, so a cropped or retouched file can still carry a preview of the original. This test compares each preview with its own image and with the other image.',
    thresholds: 'A preview that shows the other image rather than its own: match. A preview that matches neither: stale (edited after the preview was written).',
    robust: ['crops and retouching that leave EXIF alone'],
    weak: ['most web images have no preview', 'previews are easy to remove'],
    refs: [{ label: 'Kee & Farid, Digital image authentication from thumbnails (SPIE 2010)', url: 'https://doi.org/10.1117/12.838834' }],
  },
];

export const ENGINE_BY_ID = Object.fromEntries(ENGINES.map((e) => [e.id, e]));

/** Map a numeric score to a verdict using the engine's thresholds. */
export function verdictFor(engine, value) {
  if (value === null || value === undefined || Number.isNaN(value)) return 'na';
  if (engine.better === 'higher') {
    if (value >= engine.match) return 'match';
    if (engine.partial !== null && engine.partial !== undefined && value >= engine.partial) return 'partial';
    return 'none';
  }
  if (engine.better === 'lower') {
    if (value <= engine.match) return 'match';
    if (engine.partial !== null && engine.partial !== undefined && value <= engine.partial) return 'partial';
    return 'none';
  }
  return value ? 'identical' : 'none';
}

export const VERDICT_LABEL = {
  identical: 'Identical',
  match: 'Match',
  partial: 'Partial',
  none: 'No match',
  na: 'N/A',
  error: 'Error',
  skipped: 'Off',
  pending: 'Waiting',
  running: 'Running',
};
